### ISSUE TITLE
关于静态文件的建议

### ISSUE THREAD

**Issue by haiber0702** [qicosmos/cinatra#105]
目前静态文件的判断有点粗暴， 每次请求进来判断内容中有'.'的就认为是静态文件
这种设计不太好
1.  限制了URL设计  非静态文件访问URL内容不能带'.'
2.  cinatra有可能只用来做api server  每次都判断是否静态文件 带来性能开销

建议参考其他WEB框架如django 设置一个static**文件目录** 和目录的**路由** 通过路由去执行静态文件处理

**Comment by vrqq** [comment]
支持！
我觉得不用处理静态文件，直接交给nginx，前后端分离开来。
或者把处理静态文件单独分一个模块，还可优化SEO。。

**Comment by qicosmos** [comment]
这块需要重构一下，cinatra需要能够自己处理静态文件，但也允许支持nginx，这样更好一些。

**Comment by qicosmos** [comment]
done
