### ISSUE TITLE
我用py上传文件上传不了,但是使用postman却可以正常上传文件

### ISSUE THREAD

**Issue by wuyiwywy** [qicosmos/cinatra#106]
![image](https://user-images.githubusercontent.com/38450694/57212190-7a4cfa00-7015-11e9-93f6-c36ae99a3ee8.png)
![image](https://user-images.githubusercontent.com/38450694/57212221-9fda0380-7015-11e9-972c-7809b8a4d0f1.png)

**Comment by qicosmos** [comment]
抓包看看二者哪里不同。

**Comment by wuyiwywy** [comment]
py requests 传过去多了一个头信息，但是我其他的接口用这两种访问方式就没有这样的问题

**Comment by qicosmos** [comment]
用node js传呢

**Comment by wuyiwywy** [comment]
没用过node.js，主要最近用你推荐的file方式上传图片，写好整个项目，但是今天利用python调用接口发现py request上传的图片req.get_upload_files()获取不到
![image](https://user-images.githubusercontent.com/38450694/57214602-16c6ca80-701d-11e9-83e4-45fb3651c76a.png)

**Comment by qicosmos** [comment]
你打包一个上传文件的测试程序给我，我看看。

**Comment by wuyiwywy** [comment]
我用postman就可以正常上传图片，问题就是我最开始截图的那两个问题

**Comment by wuyiwywy** [comment]
void process(request& req, response& res) {
	auto& files = req.get_upload_files();
	std::string img_path;
	for (auto& file : files) {
		std::cout << file.get_file_path() << " " << file.get_file_size() << std::endl;
		img_path = file.get_file_path();
	}
	auto data = req.body();
	std::cout << "body length:" << data<< std::endl;
}

**Comment by wuyiwywy** [comment]
import base64
import requests
from urllib.parse import unquote



with open("../data/img/test1.png", "rb") as f:
    img = f.read()

headers = {"Content-Type": "form-data"}
req_url = "http://127.0.0.1:8081/"
res = requests.post(req_url, headers=headers, files={"file": img})
print(res.text)

py 的测试程序

**Comment by wuyiwywy** [comment]
要不我加你qq，截图给你看也行

**Comment by qicosmos** [comment]
你加cinatra qq群吧 340713904
