### ISSUE TITLE
python request 上传文件踩坑之一

### ISSUE THREAD

**Issue by wuyiwywy** [qicosmos/cinatra#107]
with open(img_path, "rb") as file:
        img = file.read()

    # 1.上传文件  multipart/form-data 格式一定要使用 encode_multipart_formdata 编码
    #  2. encode_multipart_formdata 编码时候一定带上文件类型。
    encode_data = encode_multipart_formdata({"file":("test1.png",
                                                     open("../data/img/test1.png", "rb").read(), "image/png")})
    headers = {"Content-Type": encode_data[1]}
    print(encode_data[1])
    req_url = "http://10.19.177.213:8081/ocr"
    res = requests.post(req_url, headers=headers, data=encode_data[0]

以上就是我上传文件时候的总结，一定要多看文档，多看文档，多看文档！！！

**Comment by qicosmos** [comment]
good
