### ISSUE TITLE
connection.hpp中 tcp_socket& socket()方法修改建议

### ISSUE THREAD

**Issue by lijixiang2010** [qicosmos/cinatra#108]
我在学习cinatra的代码。
template <typename socket_type>	class connection 类是一个模板类。其中成员变量socket_为从模板传入的socket_type类型。 然而其中的tcp_socket& socket() {return socket_;} 方法却返回tcp_socket类型。 其中tcp_socket类型是在request.hpp中定义的 using tcp_socket = boost::asio::ip::tcp::socket;
这样connection类的模板类型好像就固定死了，没有必要了。这样写是否有所不妥？
谢谢。

**Comment by qicosmos** [comment]
哦，这里之前想着还可以支持udp socket的，所以增加了一个模板参数，现在看来没有udp，显得多余了。
