### ISSUE TITLE
connection.hpp 116行有一处BUG

### ISSUE THREAD

**Issue by lijixiang2010** [qicosmos/cinatra#109]
connection.hpp 116行有一句 static_assert(size != 0 || size != 2);  显然无论size为何值都会返回true。导致断言失效。
谢谢。

**Comment by qicosmos** [comment]
请仔细看一下代码，这里限定了至少要传一个回调函数。这个断言就是限定要么是一个回调，要么是两个回调。

另外提issue的时候需要有实际的问题反馈，请经过测试确定问题之后再提。

**Comment by lijixiang2010** [comment]
好的。谢谢。
