### ISSUE TITLE
建议去掉LOG_INFO

### ISSUE THREAD

**Issue by fawdlstty** [qicosmos/cinatra#110]
日至相关的其实都可以不要，但有了这个就导致与几乎所有的日志库冲突了

**Comment by qicosmos** [comment]
也许可以加一个宏开关，默认就不打开。
你研究一下这个问题，然后提一个pr吧。

**Comment by fawdlstty** [comment]
我的看法是直接去掉LOG_INFO，，，

**Comment by qicosmos** [comment]
那一些网络异常信息就直接忽略，不输出到日志里？

**Comment by fawdlstty** [comment]
就按照扩展展开的形式？

**Comment by qicosmos** [comment]
看里面加的几个宏是和vs相关的，你还需要加一个是否为msvc的判断，不能只管vc，不管其它平台。
改成扩展形式是可以的。

**Comment by fawdlstty** [comment]
其他平台加上这几个宏丝毫不影响编译，似乎没必要加平台判断

**Comment by qicosmos** [comment]
请在linux下测试一下，我需要明确的结果。

**Comment by qicosmos** [comment]
提交pr肯定是要在几个平台都测试一下的。

**Comment by fawdlstty** [comment]
我这儿没有linux环境，，，需要其他人协助。

**Comment by fawdlstty** [comment]
今晚我可以试试WSL

**Comment by qicosmos** [comment]
ok，尽量多测几个平台。
