### ISSUE TITLE
url中带有中文的问题

### ISSUE THREAD

**Issue by zhaojiecll** [qicosmos/cinatra#122]
你好，我正在使用你们的cinatra开发一个大文件上次下载C++服务器，因为我们自己的业务，url中会出现中文的情况，我尝试了下，好像不能实现，不知道是不支持还是我代码的问题。
代码如下
    server.set_http_handler<GET, POST>("/中文测试", [](request& req, response& res) {
        res.render_string("中文测试");
    });

返回错误:the url is not right
请问是否支持url带有中文的

**Comment by qicosmos** [comment]
需要对中文的url做encode处理，类似于这样：
```
server.set_http_handler<GET, POST>("/"+code_utils::url_encode("中文"), [](request& req, response& res) {
        res.render_string(std::to_string(std::time(nullptr)));
    });
```

http://127.0.0.1:8080/中文

**Comment by zhaojiecll** [comment]
好的，非常感谢




| |
zhaojiecll
|
|
邮箱：zhaojie10300920@163.com
|

Signature is customized by Netease Mail Master

在2019年09月20日 19:26，qicosmos 写道：

需要对中文的url做encode处理，类似于这样：

server.set_http_handler<GET, POST>("/"+code_utils::url_encode("中文"), [](request& req, response& res) {

        res.render_string(std::to_string(std::time(nullptr)));

    });



http://127.0.0.1:8080/中文
