### ISSUE TITLE
http_router::map_invokers_键值类型为std::string_view

### ISSUE THREAD

**Issue by mzyxxfff** [qicosmos/cinatra#131]
由此以下代码无法运行
`void foo(cinatra::http_server *server) {`
`	std::string url("/1");`
`	server->set_http_handler<GET, POST>(std::string_view(url.c_str()), [](request &req, response &res) {`
`		res.set_status_and_content(status_type::ok, "ok");`
`	});`
`}`
在函数传值过程中形参一直为std::string_view，url销毁后map_invokers_的相应键值就无效了。

**Comment by mzyxxfff** [comment]
另外直接放到main函数中有时也会挂掉，这个没有找到原因。

**Comment by qicosmos** [comment]
string_view并不拥有string的生命周期，你这样相当于把一个临时变量作为了一个key，就会出现这个问题，不要这样用。

**Comment by mzyxxfff** [comment]
> string_view并不拥有string的生命周期，你这样相当于把一个临时变量作为了一个key，就会出现这个问题，不要这样用。

但我希望可以循环生成规律的url，现在我是push_back到list里的
