### ISSUE TITLE
set_http_handler回调里面做异步操作的问题

### ISSUE THREAD

**Issue by iamaccount** [qicosmos/cinatra#136]
目前版本里面做异步操作会貌似要出问题，里面的这两个参数cinatra::request&和cinatra::response&，可能要改成shared_ptr

**Comment by qicosmos** [comment]
最新版本里面异步操作没有问题，示例代码：
```
            res.set_delay(true);
            auto client = client_factory::instance().new_client<cinatra::NonSSL>("127.0.0.1", "8080");
            auto weak = req.get_weak_base_conn();
            client->async_send_msg("/", "", [weak, &res](auto ec, auto data) {
                if (ec) {
                    std::cout << ec.message() << "\n";
                    return;
                }

                if (auto sp = weak.lock(); sp != nullptr) {
                    auto conn = (connection<NonSSL>*)(sp.get());
                    if (!conn->has_close()) {
                        conn->send(status_type::ok, std::string(data));
                    }
                }
            });
```

**Comment by famik** [comment]
> 最新版本里面异步操作没有问题，示例代码：
> 
> ```
>             res.set_delay(true);
>             auto client = client_factory::instance().new_client<cinatra::NonSSL>("127.0.0.1", "8080");
>             auto weak = req.get_weak_base_conn();
>             client->async_send_msg("/", "", [weak, &res](auto ec, auto data) {
>                 if (ec) {
>                     std::cout << ec.message() << "\n";
>                     return;
>                 }
> 
>                 if (auto sp = weak.lock(); sp != nullptr) {
>                     auto conn = (connection<NonSSL>*)(sp.get());
>                     if (!conn->has_close()) {
>                         conn->send(status_type::ok, std::string(data));
>                     }
>                 }
>             });
> ```
没有conn->send，参考example是conn->response_now

还有个问题是有可能切面的after没执行到
