### ISSUE TITLE
代码和crow很像

### ISSUE THREAD

**Issue by xionghuy** [qicosmos/cinatra#137]
2个效率差距咋样？？

**Comment by xionghuy** [comment]
另外测试数据说几百万的  用啥机器配置 啥工具测试的欸
想找个压测工具

**Comment by qicosmos** [comment]
wrk测试的，这个测试结果是第三方评测的https://www.techempower.com/

**Comment by qicosmos** [comment]
不过貌似crow效率很低，都没有上榜。

**Comment by xkyi** [comment]
crow提供的benchmark上显示，crow和netty差不多 
https://github.com/ipkn/crow-benchmark

**Comment by qicosmos** [comment]
tfb上netty大概排名40左右。
