### ISSUE TITLE
做 restful 接口遇到的问题

### ISSUE THREAD

**Issue by yixingwang0517** [qicosmos/cinatra#141]
server->set_http_handler\<cinatra::PUT&gt;("/api/user", &UserControl::add, areaCtrl_);
server->set_http_handler&lt;cinatra::DEL&gt;("/api/user", &UserControl::del, areaCtrl_);
server->set_http_handler&lt;cinatra::POST&gt;("/api/user", &UserControl::mod, areaCtrl_);
资源路径都是 /api/user，PUT 表示新增、DEL表示删除、POST表示修改（因为不支持PATCH，所以用POST代替）。这种情况下，三种不同的请求都会进行到 UserControl::add

**Comment by qicosmos** [comment]
你应该是写错了，method不同，即使url相同也应该会路由到不同的函数里的，你可以对cinatra写一个简单的测试代码来验证。

**Comment by yixingwang0517** [comment]
期望是根据 URL + method 做路由，但是没有达到期望。改成下面这样后就可以了。
server->set_http_handlercinatra::PUT("/api/user/add", &UserControl::add, areaCtrl_);
server->set_http_handlercinatra::DEL("/api/user/del", &UserControl::del, areaCtrl_);
server->set_http_handlercinatra::POST("/api/user/update", &UserControl::mod, areaCtrl_);

**Comment by qicosmos** [comment]
没有单独测试一下cinatra吗，你这个是自己封装的方法呀。

**Comment by xmh0511** [comment]
因为 你三种方法的路由全部都指定了`UserControl::add, areaCtrl_`,所以都会进入同一种方法，你需要做的事情是三种请求进入三种不同的对应的方法，要不就通过method判断当前是那种请求，建议使用第一种方法

**Comment by qicosmos** [comment]
@yixingwang0517 
Hi, 应该cinatra的bug，我晚点修复一下，理论上url相同，但是method不同是要进不同的路由函数的。

**Comment by ivloli** [comment]
我也发现了这个问题，而且 utills里面的get_method_arr方法中，
```	template<http_method... Is>
	constexpr auto get_method_arr() {
		std::array<char, 26> arr{0};
		std::string_view s;
		((s = type_to_name(std::integral_constant<http_method, Is>{}), arr[s[0]-65] = s[0]), ...);

		return arr;
	}
```
arr取的是method的首字母，导致只要设置了POST和PUT中任意一个，发送POST或者PUT方法都会进入到注册的函数里面。
另外对于相同的url进行多次set_http_handler操作会导致后面的set_http_handler操作覆盖前面的

**Comment by famik** [comment]
```
server.set_http_handler<PUT, DEL, POST>("/api/user", [](request& req, response& res) {
    if (req.get_method() == "PUT") {
        
    } else if (req.get_method() == "DEL") {

    } else if (req.get_method() == "POST") {

    }
});
```
目前只能这样吧？

**Comment by qicosmos** [comment]
hi 你可以考虑提个pr修复一下。

**Comment by opakaj** [comment]
any solutions to this problem yet?

**Comment by qianxiaoming** [comment]
这个问题没人去解决吗？

**Comment by qicosmos** [comment]
I will fix the problem soon.
