### ISSUE TITLE
http_client.hpp 同步获取网页的问题

### ISSUE THREAD

**Issue by idigger** [qicosmos/cinatra#153]
std::string uri = "http://txt.go.sohu.com/ip/soip";
    response_data result = client->get(uri);
    print(result);  // 打印resp_body的第一个字节丢失了(实际变成\0x00)
    printf("result: %s\n", result.resp_body.data()); // 此处由于第一个字节变成\x00造成打印空串

造成以上问题是同步 client->get(uri); 里面还是异步调用，以下语句有问题
     sp->set_value({ ec, status, result, get_resp_headers() });
其中 result 是 string_view，保存的只有数据指针和大小。
read_chunk_body 中 callback 之后调用 clear_chunk_buffer(); 把指针指向的数据清空了。

以上盼尽快修复。

**Comment by qicosmos** [comment]
谢谢反馈这个问题，是一个bug，已经修复，取最新的代码即可。

**Comment by idigger** [comment]
现在好了，感谢你的快速修复，这个库很好用，愿有更多的人使用。

**Comment by qicosmos** [comment]
hi 你也可以把你们公司加入到cinatra用户列表中，列表中的用户问题会优先解决。
https://github.com/qicosmos/cinatra/wiki/%E8%B0%81%E5%9C%A8%E7%94%A8cinatra

**Comment by qicosmos** [comment]
已解决。
