### ISSUE TITLE
关于cinatra ssl名称与openssl ssl名称冲突

### ISSUE THREAD

**Issue by liushunhang** [qicosmos/cinatra#155]
因为项目中使用到了openssl库，包含了openssl库相关的头文件以后与using namespace cinatra中的SSL冲突，我目前的解决方案是using cinatra::xxxx代替using namespace cinatra;不知道有没有其他修改方案。

**Comment by Jackson-soft** [comment]
一般是不建议using namespace xxx这种写法，都是类似于std::cout 这种

**Comment by qicosmos** [comment]
是的，不要using全局。
