### ISSUE TITLE
指定了c++17标准，运行例子报错,GCC-7.5.0

### ISSUE THREAD

**Issue by 424358225** [qicosmos/cinatra#156]
error: undefined reference to `std::experimental::filesystem::v1::__cxx11::path::parent_path() const'
error: undefined reference to `std::experimental::filesystem::v1::__cxx11::path::_M_split_cmpts()'
error: undefined reference to `std::experimental::filesystem::v1::create_directories(std::experimental::filesystem::v1::__cxx11::path const&, std::error_code&)'

**Comment by qicosmos** [comment]
什么编译环境？

**Comment by 424358225** [comment]
Qt5.14，GCC7.5，Ubuntu 18.04
Qt的pro文件指定了CONFIG+=c++1z

**Comment by qicosmos** [comment]
你写一个测试代码，测试std::filesysytem, 看看filesystem到底是在标准库中还是experiment中。

**Comment by 424358225** [comment]
在experiment中。

**Comment by qicosmos** [comment]
把编译出错的文件名和行号发一下。

**Comment by 424358225** [comment]
`/tmp/ccyGvJXX.o：在函数‘std::experimental::filesystem::v1::exists(std::experimental::filesystem::v1::__cxx11::path const&, std::error_code&)’中：
main.cpp:(.text._ZNSt12experimental10filesystem2v16existsERKNS1_7__cxx114pathERSt10error_code[_ZNSt12experimental10filesystem2v16existsERKNS1_7__cxx114pathERSt10error_code]+0x2e)：对‘std::experimental::filesystem::v1::status(std::experimental::filesystem::v1::__cxx11::path const&, std::error_code&)’未定义的引用
/tmp/ccyGvJXX.o：在函数‘cinatra::upload_file::rename_file(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)’中：
main.cpp:(.text._ZN7cinatra11upload_file11rename_fileERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE[_ZN7cinatra11upload_file11rename_fileERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE]+0x80)：对‘std::experimental::filesystem::v1::rename(std::experimental::filesystem::v1::__cxx11::path const&, std::experimental::filesystem::v1::__cxx11::path const&, std::error_code&)’未定义的引用
/tmp/ccyGvJXX.o：在函数‘cinatra::http_client::download_impl(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, long, std::function<void (cinatra::response_data)>, unsigned long)’中：
main.cpp:(.text._ZN7cinatra11http_client13download_implENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES6_lSt8functionIFvNS_13response_dataEEEm[_ZN7cinatra11http_client13download_implENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES6_lSt8functionIFvNS_13response_dataEEEm]+0x6d)：对‘std::experimental::filesystem::v1::__cxx11::path::parent_path() const’未定义的引用
main.cpp:(.text._ZN7cinatra11http_client13download_implENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES6_lSt8functionIFvNS_13response_dataEEEm[_ZN7cinatra11http_client13download_implENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES6_lSt8functionIFvNS_13response_dataEEEm]+0xa1)：对‘std::experimental::filesystem::v1::create_directories(std::experimental::filesystem::v1::__cxx11::path const&, std::error_code&)’未定义的引用
main.cpp:(.text._ZN7cinatra11http_client13download_implENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES6_lSt8functionIFvNS_13response_dataEEEm[_ZN7cinatra11http_client13download_implENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES6_lSt8functionIFvNS_13response_dataEEEm]+0x266)：对‘std::experimental::filesystem::v1::file_size(std::experimental::filesystem::v1::__cxx11::path const&, std::error_code&)’未定义的引用
main.cpp:(.text._ZN7cinatra11http_client13download_implENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES6_lSt8functionIFvNS_13response_dataEEEm[_ZN7cinatra11http_client13download_implENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES6_lSt8functionIFvNS_13response_dataEEEm]+0x5c3)：对‘std::experimental::filesystem::v1::file_size(std::experimental::filesystem::v1::__cxx11::path const&, std::error_code&)’未定义的引用
/tmp/ccyGvJXX.o：在函数‘cinatra::http_client::send_multipart_msg(cinatra::context const&)’中：
main.cpp:(.text._ZN7cinatra11http_client18send_multipart_msgERKNS_7contextE[_ZN7cinatra11http_client18send_multipart_msgERKNS_7contextE]+0x122)：对‘std::experimental::filesystem::v1::file_size(std::experimental::filesystem::v1::__cxx11::path const&, std::error_code&)’未定义的引用
/tmp/ccyGvJXX.o：在函数‘std::experimental::filesystem::v1::__cxx11::path::path<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::experimental::filesystem::v1::__cxx11::path>(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)’中：
main.cpp:(.text._ZNSt12experimental10filesystem2v17__cxx114pathC2INSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES3_EERKT_[_ZNSt12experimental10filesystem2v17__cxx114pathC5INSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES3_EERKT_]+0x70)：对‘std::experimental::filesystem::v1::__cxx11::path::_M_split_cmpts()’未定义的引用
/tmp/ccyGvJXX.o：在函数‘cinatra::http_server_<cinatra::NonSSL, cinatra::io_service_pool>::http_server_<unsigned int>(unsigned int&&)’中：
main.cpp:(.text._ZN7cinatra12http_server_INS_6NonSSLENS_15io_service_poolEEC2IJjEEEDpOT_[_ZN7cinatra12http_server_INS_6NonSSLENS_15io_service_poolEEC5IJjEEEDpOT_]+0x8b)：对‘std::experimental::filesystem::v1::current_path[abi:cxx11]()’未定义的引用
main.cpp:(.text._ZN7cinatra12http_server_INS_6NonSSLENS_15io_service_poolEEC2IJjEEEDpOT_[_ZN7cinatra12http_server_INS_6NonSSLENS_15io_service_poolEEC5IJjEEEDpOT_]+0xbe)：对‘std::experimental::filesystem::v1::absolute(std::experimental::filesystem::v1::__cxx11::path const&, std::experimental::filesystem::v1::__cxx11::path const&)’未定义的引用
main.cpp:(.text._ZN7cinatra12http_server_INS_6NonSSLENS_15io_service_poolEEC2IJjEEEDpOT_[_ZN7cinatra12http_server_INS_6NonSSLENS_15io_service_poolEEC5IJjEEEDpOT_]+0x114)：对‘std::experimental::filesystem::v1::current_path[abi:cxx11]()’未定义的引用
main.cpp:(.text._ZN7cinatra12http_server_INS_6NonSSLENS_15io_service_poolEEC2IJjEEEDpOT_[_ZN7cinatra12http_server_INS_6NonSSLENS_15io_service_poolEEC5IJjEEEDpOT_]+0x147)：对‘std::experimental::filesystem::v1::absolute(std::experimental::filesystem::v1::__cxx11::path const&, std::experimental::filesystem::v1::__cxx11::path const&)’未定义的引用
/tmp/ccyGvJXX.o：在函数‘std::experimental::filesystem::v1::__cxx11::path::path<char [4], std::experimental::filesystem::v1::__cxx11::path>(char const (&) [4])’中：
main.cpp:(.text._ZNSt12experimental10filesystem2v17__cxx114pathC2IA4_cS3_EERKT_[_ZNSt12experimental10filesystem2v17__cxx114pathC5IA4_cS3_EERKT_]+0x73)：对‘std::experimental::filesystem::v1::__cxx11::path::_M_split_cmpts()’未定义的引用
/tmp/ccyGvJXX.o：在函数‘cinatra::http_server_<cinatra::NonSSL, cinatra::io_service_pool>::init_dir(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)’中：
main.cpp:(.text._ZN7cinatra12http_server_INS_6NonSSLENS_15io_service_poolEE8init_dirERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE[_ZN7cinatra12http_server_INS_6NonSSLENS_15io_service_poolEE8init_dirERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE]+0xe3)：对‘std::experimental::filesystem::v1::create_directories(std::experimental::filesystem::v1::__cxx11::path const&, std::error_code&)’未定义的引用
/tmp/ccyGvJXX.o：在函数‘cinatra::http_server_<cinatra::NonSSL, cinatra::io_service_pool>::set_static_res_handler()::{lambda(cinatra::request&, cinatra::response&)#1}::operator()(cinatra::request&, cinatra::response&) const’中：
main.cpp:(.text._ZZN7cinatra12http_server_INS_6NonSSLENS_15io_service_poolEE22set_static_res_handlerEvENKUlRNS_7requestERNS_8responseEE_clES5_S7_[_ZZN7cinatra12http_server_INS_6NonSSLENS_15io_service_poolEE22set_static_res_handlerEvENKUlRNS_7requestERNS_8responseEE_clES5_S7_]+0x34f)：对‘std::experimental::filesystem::v1::file_size(std::experimental::filesystem::v1::__cxx11::path const&, std::error_code&)’未定义的引用
main.cpp:(.text._ZZN7cinatra12http_server_INS_6NonSSLENS_15io_service_poolEE22set_static_res_handlerEvENKUlRNS_7requestERNS_8responseEE_clES5_S7_[_ZZN7cinatra12http_server_INS_6NonSSLENS_15io_service_poolEE22set_static_res_handlerEvENKUlRNS_7requestERNS_8responseEE_clES5_S7_]+0x504)：对‘std::experimental::filesystem::v1::file_size(std::experimental::filesystem::v1::__cxx11::path const&)’未定义的引用
collect2: error: ld returned 1 exit status
`

**Comment by 424358225** [comment]
g++ -o  test main.cpp -lpthread  -std=c++1z   -lboost_system -lboost_filesystem -lboost_date_time

**Comment by qicosmos** [comment]
看起来是编译选项有点问题，没有依赖boost的这些东西，加上-lstdc++fs
另外，cinatra已经提供了cmake工程，直接
mkdir build
cd build
make -j
就完了。为啥要自己搞一堆，先把例子跑起来会事半功倍。

**Comment by 424358225** [comment]
`/home/td/SDK/cinatra/example/../include/cinatra/use_asio.hpp:6:10: fatal error: asio.hpp: 没有那个文件或目录
 #include <asio.hpp>
          ^~~~~~~~~~
compilation terminated.
CMakeFiles/cinatra_example.dir/build.make:62: recipe for target 'CMakeFiles/cinatra_example.dir/main.cpp.o' failed
make[2]: *** [CMakeFiles/cinatra_example.dir/main.cpp.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/cinatra_example.dir/all' failed
make[1]: *** [CMakeFiles/cinatra_example.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2
`  cmake的时候报这个

**Comment by 424358225** [comment]
最开始是cmake编译的，我看别的issus里用了gcc指令 所以就拿那个试了一下

**Comment by qicosmos** [comment]
你用cmake编译吧，把cmakelist里面的Standalone开关关掉，默认是依赖独立版的asio而不是boost的，关掉开关之后就会依赖boost asio了。

**Comment by 424358225** [comment]
非常感谢您^_^
