### ISSUE TITLE
异常没有捕获会导致init_conn_callback一直失败。

### ISSUE THREAD

**Issue by Kidsunbo** [qicosmos/cinatra#160]
使用cinatra搭建了一个服务器，当客户端异常退出时可能导致socket没有正确关闭，出现write() send(): Broken pipe exception in business function错误。此时此URL无法正常访问，所有的链接都会出现此错误。
请问如何解决这一个问题呢？

**Comment by qicosmos** [comment]
请把一个简单的测试代码贴上来。

**Comment by Kidsunbo** [comment]
查到是内部的一个微服务挂了导致每次都请求异常。感谢回复:)
