### ISSUE TITLE
response的好几个成员函数没有，是我配置的问题嘛？

### ISSUE THREAD

**Issue by lzzkdxc** [qicosmos/cinatra#162]
res.set_attr()没有，res.render_view()没有，feather里的res.render_json()也没有，还没做吗，还是我没配置好？
![image](https://user-images.githubusercontent.com/36161570/95284831-cd258380-0891-11eb-8c95-60475559a3dc.png)
![image](https://user-images.githubusercontent.com/36161570/95284844-d7e01880-0891-11eb-8876-a1a616d9ecd5.png)

**Comment by lzzkdxc** [comment]
![image](https://user-images.githubusercontent.com/36161570/95289798-41662400-089e-11eb-9403-c41953262a11.png)
还有这个也没有诶

**Comment by qicosmos** [comment]
render_json去掉了，json属于上层应用的，由用户自己选用合适的json库，自己封装一个render json方法就好了，可以参考之前的实现。
