### ISSUE TITLE
服务进程占用内存随访问负载智能变化的问题

### ISSUE THREAD

**Issue by zdy333666** [qicosmos/cinatra#163]
随着web访问负载增加,服务进程占用内存随之增多，访问负载消失后，服务进程占用的内存依然保持着之前的最大值。能否让内存占用随访问负载的增减而自动扩大或缩小？

**Comment by qicosmos** [comment]
是最新的代码吗？等一段时间内存应该会慢慢降低下来的。

**Comment by gqw** [comment]
@zdy333666 可以用pmap查看下内存分配情况，以前线上项目遇到过类似的情况，看看是不是linux glic的arena内存池导致的，在64位机器上每个进程最多会分配 (8*cpu核数+1)*64MB的内存，算下来能还是挺恐怖的，这些内存一般不会主动释放，只有在系统内存吃紧的时候才会释放。关于Arena内存管理可参考：https://segmentfault.com/a/1190000005118060

**Comment by qicosmos** [comment]
已经加了shrink_memory的设置用来实时降低内存占用。
