### ISSUE TITLE
第一次连接上之后接受分段大数据，服务器无法收到消息

### ISSUE THREAD

**Issue by danche-cc** [qicosmos/cinatra#166]
用cinatra做服务器，客户端是从一个容器里发送http请求，但是这个容器底层应该设置了mss，是1496，比较小，每次第一次连接的时候，发送比较大的数据就会分段发送，这时候cinatra服务器就收不到数据了，抓包看都正常，如果先发个小数据，再发大数据又是能正常接收的
![1](https://user-images.githubusercontent.com/11610325/98060004-86707c80-1e83-11eb-9449-19daae226b34.png)
![2](https://user-images.githubusercontent.com/11610325/98060005-87a1a980-1e83-11eb-9b29-4ab22b31c51a.png)

**Comment by qicosmos** [comment]
OK, 晚点确认一下。

**Comment by qicosmos** [comment]
可以测试一下最新代码吗？
