### ISSUE TITLE
get_query_value的问题

### ISSUE THREAD

**Issue by akoon** [qicosmos/cinatra#173]
server.set_http_handler<GET, POST>("/pathinfo/*", [](request& req, response& res) {
	auto s = req.get_query_value(0);
	res.render_string(std::string(s.data(), s.length()));
});
这种用法是不是不能用了，我记得以前是可以的，现在获取到的是空

**Comment by qicosmos** [comment]
可能时候是后面改的时候去掉了，我晚点加上这个接口。

**Comment by qicosmos** [comment]
测试了这个用法没问题啊。
request url: http://127.0.0.1:8090/pathinfo/b?a=1&b=2  或者 http://127.0.0.1:8090/pathinfo/a?a=1&b=2
```c++
  server.set_http_handler<GET, POST>("/pathinfo/*", [](request &req, response &res){
    auto s1 = req.get_query_value(0);
    auto s2 = req.get_query_value(1);
    std::cout<<s1<<" "<<s2<<'\n';
    res.set_status_and_content(status_type::ok, "ok");
  });
```
都可以打印出1 2
