### ISSUE TITLE
上传文件无法对上传的文件进行区分

### ISSUE THREAD

**Issue by Hotege** [qicosmos/cinatra#174]
例如我使用curl URL -F "f1=1.txt" -F "f2=2.txt" ...上传多个文件，req.get_upload_files()只能获取到上传的多个文件，不能通过f1、f2这些key对文件进行区分。

可能是我没找到正确的调用姿势，如果能够区分请指出。

**Comment by qicosmos** [comment]
这个可能还没处理，我晚点看一下。

**Comment by qicosmos** [comment]
用最新的方式没这个问题
