### ISSUE TITLE
Render

### ISSUE THREAD

**Issue by opakaj** [qicosmos/cinatra#178]
Why do I get a read access violation error when implementing render.
This is the code.
server.set_http_handler("/data", [](const request& req, response& res) {
    res.set_attr("person",inja::json{{"name","xmh"},{"age",30}});
    res.render_view("./data.html");
});

I replaced ninja with nlohmann

**Comment by qicosmos** [comment]
Is 'inja::json{{"name","xmh"},{"age",30}}' a string?

**Comment by opakaj** [comment]
![inja](https://user-images.githubusercontent.com/78092188/106186190-fb1e3300-61b4-11eb-91b1-3b211fb6ee0a.png)
That's how the code is...shows no errors till you run the debbuger. I got it from purecpp website.

**Comment by opakaj** [comment]
It produces a read access violation

![Uploading render.png…]()

**Comment by opakaj** [comment]
That's how it looks
![Uploading render.png…]()

**Comment by opakaj** [comment]
Apparently,  holder_ is returning a null ptr with that code. (In render.h)
