### ISSUE TITLE
Template usage

### ISSUE THREAD

**Issue by opakaj** [qicosmos/cinatra#179]
So, I have bootstrap templates written in css,html, and some jquery and js. Is it possible to use them instead and just edit some simple html code, and provide the necessary changes for render to do its thing, the  finally handle the routing from forms and buttons to the server for processing and back.
If so, kindly enlighten me on how that would be done.

**Comment by qicosmos** [comment]
Of course you can, similar with this: https://github.com/qicosmos/feather/blob/master/purecpp/html/home.html#L65

BTW: Where are you from, a beginner of c++?

**Comment by opakaj** [comment]
No. M just amazed by render.never thought it was possible with c++. From East Africa.
