### ISSUE TITLE
希望介绍页面或set_handler等关键地方增加注释: 关于多线程的注解

### ISSUE THREAD

**Issue by sleepreading** [qicosmos/cinatra#180]
用户非常关注以下两点:

- 每一个注册的回调函数, **回调函数体本身的执行都是线程安全的吗**? 如果并发N个用户调用一个接口. 自定义的回调函数内部逻辑是否会错乱? 也就是是否需要加锁. 或者什么情况下需要加锁?
- 如果并发了N个调用. 假设只对应了一个回调函数. 此回调函数无限期阻塞了(如遇到网络问题,可能阻塞76s等等). 那么 **N 为多大时,后续的调用就会跟着一起阻塞**? 内部实现应该是线程池吧. 但如果阻塞调用的队列过大, 想知道: 是否会对整体服务质量有影响? 还是说, 不管阻塞了多少个调用. 都不会对后续的调用带来任何影响?

**Comment by qicosmos** [comment]
回调本身是线程安全的，回调函数内部你要处理共享资源的时候需要加锁，和业务相关，线程安全性由用户自己控制。
如果回调函数所在的线程是io线程，不要阻塞，如果耗时的操作应该丢到线程池中处理。如果阻塞了io线程，后续的回调不会触发，所以不要阻塞io线程。
