### ISSUE TITLE
Byte is ambiguous / namespace std has no member byte

### ISSUE THREAD

**Issue by opakaj** [qicosmos/cinatra#182]
I get the error; byte is not a member of std from utils.h
Why.

**Comment by qicosmos** [comment]
It's a c++17 feature, i have provided example, you can build and run the example firstly.

**Comment by opakaj** [comment]
How would you implement a loop that has json render, for example 50 numbers/names. Within the same controller function. I've tried many times but the request fails

**Comment by qicosmos** [comment]
It's easy, you can chose a json library, and build the json object, then send the json string.

bellow is pseudo code：

```c++
Json json;
for(auto& pair : v){
  json[pair.first] = pair.second;
}

.....
res.set_status_and_content(ok, json.dump());
```

**Comment by opakaj** [comment]
I'm trying to make a request with query parameter that has a length of 256 characters but I get iterator errors from Microsoft's xstring file. How can I resolve this so as to make a post or get method with such length.

**Comment by opakaj** [comment]
Any recommendations on the preferred hosting service to use in order to host cinatra web server. Do you use amazon lambda? Or a docker image exists?
