### ISSUE TITLE
MFC工程里使用cinatra，在debug下编不过

### ISSUE THREAD

**Issue by icegull** [qicosmos/cinatra#185]
MFC工程里使用cinatra，在debug下编不过，因为utils.hpp里的http_method::TRACE会和ATl里的TRACE冲突()，请修正， 谢谢。

Error:
Error	C2143	syntax error: missing '}' before 'ATL::CTraceFileAndLineInfo'	inc\cinatra\utils.hpp	197

**Comment by qicosmos** [comment]
带cinatra命名空间就没这个问题吧，TRACE在cinatra命名空间下和MFC的应该不会冲突。

**Comment by icegull** [comment]
> 带cinatra命名空间就没这个问题吧，TRACE在cinatra命名空间下和MFC的应该不会冲突。

	const std::string data = createJson(param);
	auto client = cinatra::client_factory::instance().new_client();
	cinatra::response_data result = client->post(m_uri, data);

我就三句话，请问在哪里加命名空间？

**Comment by qicosmos** [comment]
试试最新代码能不能在MFC下编译过。

**Comment by qljsky** [comment]
调整一下头文件加载顺序，将#include <cinatra.hpp> 放在mfc 的afx.h之前 可以避免
