### ISSUE TITLE
Https

### ISSUE THREAD

**Issue by opakaj** [qicosmos/cinatra#189]
I'm working on an API with cinatra and it has basic http verbs. Now my query is, if I set it up as a docker image, uploaded it to the cloud and bought it a domain name e.g api.something.com then gave it https capabilities with certbot. Wouldn't this implementation still work? so I wouldn't need to implement the canara https version.
In so doing, communication would work well via https.

**Comment by qicosmos** [comment]
Look at this example: https://github.com/qicosmos/cinatra/blob/master/example/main.cpp#L37
