### ISSUE TITLE
Modify Request Max Buffer Size

### ISSUE THREAD

**Issue by dataBaseError** [qicosmos/cinatra#202]
Is there an way to modify the maximum request buffer size for a server?

Updating the request's max buffer size through the `set_max_req_buf_size` does not actually update the maximum buffer size of the request. https://github.com/qicosmos/cinatra/blob/ad0101a0af35445bf6624202a84dc77b98517f59/include/cinatra/http_server.hpp#L154

Instead, for every request `MaxSize` is used. https://github.com/qicosmos/cinatra/blob/ad0101a0af35445bf6624202a84dc77b98517f59/include/cinatra/request.hpp#L831

Furthermore the previously referenced function `set_max_req_buf_size` only appears to pass through the value to the `connection`. Which then assigns the value  (`MAX_REQ_SIZE_`) but never uses it. https://github.com/qicosmos/cinatra/blob/ad0101a0af35445bf6624202a84dc77b98517f59/include/cinatra/connection.hpp#L39

**Comment by qicosmos** [comment]
最新代码去掉了这个代码。
