### ISSUE TITLE
Keep alive does not work when serving static files.

### ISSUE THREAD

**Issue by Kidsunbo** [qicosmos/cinatra#203]
I found that the connection will always be closed when serving static files even I use `HTTP/1.1` or specify `Connection: Keep-Alive`.
I have checked the source code and there is no `do_read()` in the callback of `write_chunked_data` and the server will close the connection when chunked data has been all read, the state will be `data_end` in the source code and just close the connection without checking.
Why does not  cinatra support `Keep-Alive` for chunked data?

**Comment by qicosmos** [comment]
it's a bug, please try to fix it.

**Comment by Kidsunbo** [comment]
Fix in #204

**Comment by Kidsunbo** [comment]
> it's a bug, please try to fix it.

I am confused, why can <a href="http://purecpp.org/">purecpp website</a> support keep-alive when serving static files but cinatra seems not to work with it? Some of the static files are with header containing `Server: cinatra`.

**Comment by Kidsunbo** [comment]
OK, the problem is caused by commenting some code to send small file.
Just uncomment it and everything works fine now.
I think purecpp uses. the old version so it does well.
