### ISSUE TITLE
WebSocket客户端

### ISSUE THREAD

**Issue by Bruce-Oases** [qicosmos/cinatra#208]
你好，我希望能使用cinatra实现Websocket服务端的同时也做一个简单的websocket客户端测试工具，请问如何实现使用Cinatra编写websocket客户端呢？

**Comment by xland** [comment]
看这里：https://github.com/qicosmos/cinatra#web-socket

**Comment by qicosmos** [comment]
需要注意的一个细节是需要保证client 的生命周期，在client 连接服务器之前设置读回调。

**Comment by 51bitquant** [comment]
> 看这里：https://github.com/qicosmos/cinatra#web-socket

可以提供一个能运行的demo吗？连接成功后on_msg没有信息。

**Comment by qicosmos** [comment]
用最新的client即可
