### ISSUE TITLE
The limit of request head has been fixed to 32 which may not be enough in some senario.

### ISSUE THREAD

**Issue by Kidsunbo** [qicosmos/cinatra#211]
Recently I use cinatra as a server of Faas, which will add some headers into the request. Unfortunately, the number reaches the limitation, which is 32 in the code. Then the request will be aborted and return `400 Bad Request` to the client. which is weird.
There seems no way to config this number because it's hard-coded into the code. Could you please consider change it to be configurable?
The code is at `requests.hpp:837`, which is `struct phr_header headers_[32];`.

**Comment by Kidsunbo** [comment]
Or maybe a little bigger maybe? such as 64.

**Comment by qicosmos** [comment]
OK, can be 64
