### ISSUE TITLE
multipart 处理方式能导致任意文件上传

### ISSUE THREAD

**Issue by kur4ge** [qicosmos/cinatra#214]
代码中对于 multipart 文件数据都会存储到文件中。（该操作在解析http请求时进行，无论代码是否需要使用这个文件）
https://github.com/qicosmos/cinatra/blob/df5654533ecd7929a29bf48a085ee20e54bf48d5/include/cinatra/connection.hpp#L843-L860
而默认配置 static_dir_ 为相对路径www，有可能能被直接访问。
建议能修改这个路径为 /tmp 或者其他临时路径中，由开发者进行处理。

**Comment by qicosmos** [comment]
晚点看一下，谢谢指出。

**Comment by qicosmos** [comment]
最新代码已经fix
