### ISSUE TITLE
在哪里可以获取到上传文件的名字呢？

### ISSUE THREAD

**Issue by Kidsunbo** [qicosmos/cinatra#215]
cinatra好像会将上传的文件重命名，可是如果我想获取到它本身的名字应该怎么做呢？没有找到对应的接口。

**Comment by qicosmos** [comment]
设置一下[回调](https://github.com/qicosmos/cinatra/blob/master/include/cinatra/http_server.hpp#L228)，在这个回调里获取文件名.

**Comment by qicosmos** [comment]
最新方式文件名交给用户自定义了。
