### ISSUE TITLE
高并发下使用get_upload_files 会获取正在上传的文件。

### ISSUE THREAD

**Issue by ldoublej** [qicosmos/cinatra#216]
![image](https://user-images.githubusercontent.com/42720586/157004341-2af4a962-87cd-48b7-9d0b-be8fae189df5.png)
如图，正常情况下获取的文件后缀是不带_ing的。

**Comment by qicosmos** [comment]
晚点看下。

**Comment by qicosmos** [comment]
hi 能帮助再测试一下最新代码吗，应该已经fix了。

**Comment by qicosmos** [comment]
最新方式把文件细节交给用户了。
