### ISSUE TITLE
请问有没有办法脱离Boost库进行编译？

### ISSUE THREAD

**Issue by Lucy2003** [qicosmos/cinatra#230]
如题，ASIO可以独立，但是Boost.System好像不行？

是否有任何参数可以配置呢？万望不吝赐教！

**Comment by qicosmos** [comment]
可以不依赖boost，参考https://github.com/qicosmos/cinatra/blob/master/example/CMakeLists.txt#L16

**Comment by Lucy2003** [comment]
那请问如何指定ASIO的include路径呢？

**Comment by qicosmos** [comment]
asio在github上下载下来，然后包含asio头文件就可以了，它是header only的。

**Comment by Lucy2003** [comment]
好的，多谢

**Comment by Lucy2003** [comment]
此外，提个建议，在example的CMakeList.txt中添加 对Win32平台的 wsock32 和 ws2_32 等必须库的链接选项，以便使用MinGW-w64编译！:-)
