### ISSUE TITLE
开发RESTful服务端时如何设定路径参数？

### ISSUE THREAD

**Issue by qianxiaoming** [qicosmos/cinatra#237]
如何设定和获取在URL中的参数呢？比如：
http://localhost/api/v1/datasets/{setid}/items/{itemid}
如何设定这种url中的路径参数并在响应函数中获取值呢？是否支持？

**Comment by qicosmos** [comment]
目前还没支持，作为一个feature还是要支持一下。

**Comment by helintongh** [comment]
在 [pr](https://github.com/qicosmos/cinatra/pull/326/files) 已经支持了该功能。
