### ISSUE TITLE
http_client如何取消请求

### ISSUE THREAD

**Issue by famik** [qicosmos/cinatra#238]
http_client 有个close函数，但没有公开，是否可以公开close函数用于取消请求

**Comment by qicosmos** [comment]
析构http_client就可以close了，目前是用RAII去close的。

**Comment by famik** [comment]
> 析构http_client就可以close了，目前是用RAII去close的。

其实我是想结合rxcpp来使用，因为是异步的，需要用shared_ptr来管理内存，因为引用计数减少不了，所以不会析构
`
    rxcpp::observable<response_data> http_request(
            std::shared_ptr<http_client> &client,
            http_method method, std::string uri,
            req_content_type type = req_content_type::json,
            size_t timeout = 15, std::string body = "") {
        
        return rxcpp::observable<>::create<response_data>([
                client, method, uri, type, timeout, body = std::move(body)](const rxcpp::subscriber<response_data>& emitter) {
            client->async_request(method, uri, [emitter](response_data data) {
                if (data.ec) {
                    emitter.on_error(std::make_exception_ptr(std::system_error(data.ec, "Http")));
                } else {
                    emitter.on_next(std::move(data));
                    emitter.on_completed();
                }
            }, type, timeout, body);
            emitter.add([client] {
                client->close();
            });
        });
    }
`

**Comment by famik** [comment]
> 析构http_client就可以close了，目前是用RAII去close的。

问题是 http_client 在请求结束之前是不会析构的，因为没办法减少 shared_ptr 引用计数

**Comment by qicosmos** [comment]
用智能指针创建client，设置它为null来析构client

**Comment by famik** [comment]
> 用智能指针创建client，设置它为null来析构client

智能指针必须是shared_ptr，因为用了enable_shared_from_this，异步请求时lambada会捕获shared_from_this，是没办法将lambada捕获的智能指针设置为null的

**Comment by qicosmos** [comment]
OK, 我把close放出来

**Comment by qicosmos** [comment]
close放出来也没有效果，因为即使在连接之前关闭socket，仍然会连接成功，数据发送和接收都成功，一个办法是在读成功之后如果判断外面已经close socket了，就丢弃数据并退出client？这个是否满足你的需求？

**Comment by qicosmos** [comment]
代码已经更新了，close是public的，你可以测一下

**Comment by famik** [comment]
> 代码已经更新了，close是public的，你可以测一下

可以了，非常感谢
