### ISSUE TITLE
http client upgrade to C++20, use coroutine

### ISSUE THREAD

**Issue by qicosmos** [qicosmos/cinatra#240]
There are many work items to do:

- [x] 1. add CI for cinatra;
- [x] 2. refactor cmakelists
- [x] 3. add unit tests;
- [x] 4. coverage
- [x] 5. add more examples;
- [x] 6. import coroutine libraries(async_simple);
- [x] 7. refactor client with coroutine;
- [x] 8. add more functions to client(ranges download);
- [x] 9. import cinatra coro http client into yalantinglibs;
- [x] 10. proxy
- [x] 11. multipart upload
- [x]  multipart upload file > 2G
- [x] 12. web socket
- [x] 13. https
- [x] 14. timeout 
- [ ] 15. show progress when upload/download
- [x] 16. redirect
- [ ] 17. multiple thread send ws msg

**Comment by helintongh** [comment]
I want to do refactor server with coroutine and add more function.

**Comment by qicosmos** [comment]
i will own 5 and 7.

**Comment by zhengjian526** [comment]
I will complete item 2 and part of the item 3，add some unit tests.

**Comment by tianyime** [comment]
I want to take the task 1 firstly, thanks.

**Comment by ptbxzrt** [comment]
I want to participate in task 6 and 8.

**Comment by qicosmos** [comment]
almost done
