### ISSUE TITLE
编译失败 Clang-6.0 osx

### ISSUE THREAD

**Issue by NickyVSTaiMokWong09** [qicosmos/cinatra#29]
编译时出现3种错误
<img width="969" alt="8721b3cb-2b2a-4d38-9593-9b4b5c7ac838" src="https://user-images.githubusercontent.com/13817362/39934101-5f9d1c1c-5577-11e8-9119-1f68f96b3432.png">
<img width="969" alt="77788c44-014b-4d65-981a-1e9b309698b1" src="https://user-images.githubusercontent.com/13817362/39934105-6088e2fa-5577-11e8-9fe3-5e4b8115e245.png">

**Comment by NickyVSTaiMokWong09** [comment]
Gcc-7.3 完全没有任何问题
Clang下尝试过更改，越改越不知所云
望解决😔

**Comment by qicosmos** [comment]
@NickyVSTaiMokWong09 你更新一下代码再编译一下看看还有没有错误。

**Comment by NickyVSTaiMokWong09** [comment]
@qicosmos 编译通过，解决了😊，谢谢
