### ISSUE TITLE
refactor cinatra server

### ISSUE THREAD

**Issue by qicosmos** [qicosmos/cinatra#297]
main tasks:

- [x] provide a http press tool with coro_http_client
- [x] refactor cinatra server with coroutine;
- [x] add unit tests;
- [x] add more examples;
- [x] add more functions to server(support restfull url);
- [x] support nginx conf;
- [x] import cinatra server into yalantinglibs;

**Comment by helintongh** [comment]
http press tool requires command line parsing.Can I use [this](https://github.com/tanakh/cmdline).
support nginx conf and load balancer I can do.

**Comment by qicosmos** [comment]
I' m not sure if it supports win
