### ISSUE TITLE
头文件中定义全局函数导致重定义错误

### ISSUE THREAD

**Issue by tinkerlin** [qicosmos/cinatra#37]
1. utils.hpp  line:471  **get_cookies_map()**
2. utils.hpp line:254 **from_urldecode()**
3. uuid.h     line:775 **to_string()**
4. uuid.h     line:782 **to_wstring()**
以上都被定义为全局函数。

之所以会发现这个问题，是我在对cinatra进行封装时发现的。
pass以上问题之后，我又发现session_manager的成员变量也会出现重定义错误。
这里我可以通过注释掉成员变量的定义，取而代之在cpp文件中定义来解决。
但不知道有没有更好的办法（我反正是没想出来 = =

`
    session_manager{
        ......
        private:	
        static std::map<std::string, std::shared_ptr<session>> map_;
        static std::mutex mtx_;
        static int max_age_;
    };
    std::map<std::string, std::shared_ptr<session>> session_manager::map_;
    std::mutex session_manager::mtx_;
    int session_manager::max_age_ = 10 * 60;

`

**Comment by qicosmos** [comment]
好的，晚点我看一下。

**Comment by qicosmos** [comment]
这些问题应该都改过了，你更新最新代码试试。
