### ISSUE TITLE
coro_http_client 不支持多线程调用？

### ISSUE THREAD

**Issue by ganyao114** [qicosmos/cinatra#378]
上一个请求还未完成的时候再次请求会会返回 404

**Comment by qicosmos** [comment]
client 不支持多线程，client 是基于协程的，你用多线程不如用多协程。

**Comment by qicosmos** [comment]
没明白你的场景，可以写个伪代码来看看要怎么用。

**Comment by ganyao114** [comment]
https://github.com/taptap/TapSDK-CPP/commit/cb37b25f5af72bc82614cb150a6ca452962f1fff#diff-4a067907ed8ad0d226c9e6ee374a40d55b60d4e7f21571a62db79173d138accd

**Comment by qicosmos** [comment]
为了性能更好，最好不用使用同步接口，你应该用co_await client.async_post/get 这类的接口，这类接口是异步的，不会阻塞调用线程。
如果你希望同时发起多个请求，可以使用collectall，参考这个代码：
https://github.com/qicosmos/cinatra/blob/master/press_tool/main.cpp#L148

**Comment by poor-circle** [comment]
client不是线程安全的。
有两个选择:
1.不复用client。请求会在一个全局线程池中处理。
2.需要复用链接，此时你需要一个channel。
你可以使用yalantinglibs里面的coro_io::channel<coro_http::coro_http_client>。

channel是线程安全的，而client不是线程安全的。

**Comment by ganyao114** [comment]
> 
Thx
