### ISSUE TITLE
.gitignore 应该排除 build.cmake 文件

### ISSUE THREAD

**Issue by AmzGrainRain** [qicosmos/cinatra#390]
我的 vs 会在 `解决方案浏览器` 里隐藏与 `.gitignore` 文件内部规则匹配的文件。但 `cmake/build.cmake` 也被隐藏了。建议在 `.gitignore` 底部加一行 `!cmake/build.cmake` 来避免这个不方便的小问题。

**Comment by helintongh** [comment]
@qicosmos 这个需要修改吗？

**Comment by qicosmos** [comment]
那就加一下吧。
