### ISSUE TITLE
重定向问题

### ISSUE THREAD

**Issue by xmq731** [qicosmos/cinatra#398]
async_get能不能支持多层的重定向，修改函数内部async_request为async_get造成死循环，感觉哪里没有彻底清理

**Comment by qicosmos** [comment]
有没有测试链接。

**Comment by xmq731** [comment]
链接地址:http://mp.weixin.qq.com/s?__biz=MzAwNjY4MjQwMA==&mid=2650551676&idx=2&sn=ef06cd3d1432416c651a8ec4cd4b9742&chksm=83013733b476be25fbc2f3a395f0f382704cf662cbc960094ab68ec0ebf5664850f76c5ea22f&mpshare=1&scene=23&srcid=0821pWYIZLHXFmA09kpIt8gh&sharer_sharetime=1692623653568&sharer_shareid=ac54aa839b1181594a951457649994a4#rd
重定向为https地址

**Comment by qicosmos** [comment]
@helintongh 看一下多次重定向的问题。

**Comment by helintongh** [comment]
收到

**Comment by helintongh** [comment]
这个网址不是多重定向的问题。根据抓包微信文章使用了ocsp协议。如果是以http去访问触发ocsp协议，需要客户端按照ocsp方法去认证证书然后将连接转换为https才能连上。目前cinatra未支持，curl也未支持。直接通过https访问即可
![image](https://github.com/qicosmos/cinatra/assets/20508859/28113aac-589e-4a4e-a274-181292ce0d6b)
