### ISSUE TITLE
http响应数据解析有情况

### ISSUE THREAD

**Issue by xmq731** [qicosmos/cinatra#400]
测试链接：http://6.push2.eastmoney.com/api/qt/clist/get?pn=1&pz=10000&po=1&np=1&fs=m:0+t:6,m:0+t:80,m:1+t:2,m:1+t:23,m:0+t:81+s:2048&fields=f12,f14,f13
返回的body体是utf-8格式的json字符串，使用struct_json::parse解析时好时坏，QJson跟nlohmann::json一直无法通过

**Comment by qicosmos** [comment]
@bbbgan 可以看看json 解析这个问题。

**Comment by bbbgan** [comment]
> @bbbgan 可以看看json 解析这个问题。

好的，我晚一点的时候看看

**Comment by bbbgan** [comment]
测试代码
```c++
struct diff_t {
  std::string f12;
  int f13;
  std::string f14;
};
REFLECTION(diff_t, f12, f13, f14);
struct data_t {
  int total;
  std::vector<diff_t> diff;
};
REFLECTION(data_t, total, diff);
struct test_issue_t {
  int rc;
  int rt;
  long long svr;
  int lt;
  int full;
  std::string dlmkts;
  data_t data;
};
REFLECTION(test_issue_t, rc, rt, svr, lt, full, dlmkts, data);

void test() {
  test_issue_t t;
  iguana::from_json(t, str);
  std::cout << t.data.diff.size() << std::endl;
  std::cout << t.data.diff.back().f14 << std::endl;
}
```
输出正常：
```bash
5507
鼎智科技
```
目前没有发现问题，还能提供更多细节吗，比如你的测试代码，以及出错的时候是什么样子的？解析错误或者解析出来的东西有问题？

**Comment by bbbgan** [comment]
test code:
```c++
void test_parse() {
  iguana::jvalue jv;
  iguana::parse(jv, str); 
  auto data = jv.at<iguana::jobject>("data");
  auto diff = data["diff"].to_array();
  std::cout << diff.size() << std::endl;
}
```
output:
```bash
5507
```
也没有发现问题

**Comment by xmq731** [comment]
不是json库的问题,我意思http获取的数据可能有问题，使用beast库就没有问题

**Comment by qicosmos** [comment]
返回的body 是string_view, 它的生命周期和本次请求响应的生命周期一致，如果你有延迟调用body的场景，就需要注意了，这时候是需要拷贝出来的。

把你的测试代码也发出来。

**Comment by xmq731** [comment]
auto input = std::make_shared<http_input>();
input->uri = "http://6.push2.eastmoney.com/api/qt/clist/get?pn=1"
		"&pz=10000&po=1&np=1&fs=m:0+t:6,m:0+t:80,m:1+t:2,m:1+t:23,m:0+t:81+s:2048&"
		"fields=f12,f14,f13";
auto output = co_await http_op(input);
try {	
auto& r = output.res;
struct_json::jvalue j;
struct_json::parse(j,r.resp_body.begin(), r.resp_body.end());
    }catch(...){}
output定义如下：
struct http_output {
	resp_data res;
	std::shared_ptr<coro_http_client> client;
};http_op就是简单的封装一下coro_http_client，把client直接传出来了

**Comment by qicosmos** [comment]
解析失败的时候返回的body和正常的body打印一下，看看差别是什么。
另外代码要确保是master最新代码哈，最近做了一些fix。

**Comment by qicosmos** [comment]
http_op的实现怎么写的？
另外你直接co_await client.get 就可以拿到结果了，代码还更简单，为啥还要再封一层。

**Comment by xmq731** [comment]
好的，代码是昨天pull的，晚点我操作一下，这字符串唯一不一样的就是含有全角字符。封装的动机就是需要同时获取多个网站的数据，http、https都有，http重定向到https，或者https重定向到http的情况

**Comment by qicosmos** [comment]
什么情况下会失败，含有全角字符的时候会失败？能发现规律吗，什么时候会稳定出现失败？

**Comment by xmq731** [comment]
![QQ截图20230828210006](https://github.com/qicosmos/cinatra/assets/12060840/e19e00ea-8997-4ae6-9da8-badaa3d34e2f)
字符串里面的数字"零"解析为不可见字符，前面大约两百个字符串却是正常的

**Comment by xmq731** [comment]
郁闷了，取消QTextCodec::setCodecForLocale(QTextCodec::codecForName("UTF-8"))，struct_json::parse没问题了，nlohmann::json依然报异常"Unknown exception"

**Comment by xmq731** [comment]
感觉问题出在函数handle_read
![QQ截图20230829093314](https://github.com/qicosmos/cinatra/assets/12060840/38430b31-d1ba-4d66-82c2-85e1d7e1ff1e)
数据确实写入了body_里面，但是body_的size却并没有变化，所以后面set_string_end写错了位置，添加了一个'\0'

**Comment by qicosmos** [comment]
对，应该是\0 写错了位置，今天就会修复这个问题，修复之后你再验证一下。

**Comment by qicosmos** [comment]
已经fix了，你能拉一下最新代码再测一下吗？@xmq731

**Comment by qicosmos** [comment]
另外，你能加一下cinatra 用户qq 群545605838 吗，讨论也会更及时。

**Comment by qicosmos** [comment]
我也测试了一下你这个链接，返回的数据都是完整的。

**Comment by xmq731** [comment]
代码已拉，目前测试没发现问题，谢谢
