### ISSUE TITLE
websocket服务端一些问题

### ISSUE THREAD

**Issue by romanholidaypancakes** [qicosmos/cinatra#411]
1. 没有实现`ping/pong`
2. 没有实现定时器

有计划加上吗，主要是第二点

**Comment by helintongh** [comment]
定时器是指超时检测吗？

**Comment by qicosmos** [comment]
ping pong 是有实现的，不知道你说的没有实现ping pong是怎么测试的。

**Comment by qicosmos** [comment]
> > ping pong 是有实现的，不知道你说的没有实现ping pong是怎么测试的。
> 
> 我看了源码似乎仅实现了
> 
> https://github.com/qicosmos/cinatra/blob/2e4288f81a51e1d6ec7ff2e0b3c34e2f2566c776/include/cinatra/connection.hpp#L1483
> 
> ```c++
> inline constexpr data_proc_state ws_open = data_proc_state::data_begin;
> inline constexpr data_proc_state ws_message = data_proc_state::data_continue;
> inline constexpr data_proc_state ws_close = data_proc_state::data_close;
> inline constexpr data_proc_state ws_error = data_proc_state::data_error;
> ```
> 
> 应该还有`on_ping`/`on_pong`/`on_timer`, 又或许这个库设计和我看的其他库不一样我没找到吗

你看的其它库是什么库？

**Comment by qicosmos** [comment]
不符合预期，应该要触发on_close, @helintongh 你有时间先看一下这个问题吧。

**Comment by helintongh** [comment]
收到，周末改

**Comment by helintongh** [comment]
在这个 [pr](https://github.com/qicosmos/cinatra/pull/420) 已经修复该bug。
server目前调用stop函数会向连接了的websocket客户端发送close命令。

**Comment by helintongh** [comment]
websocket服务端还有另外一个问题，而是接受到客户端的ping后没有重置定时器导致客户端断联。[pr426](https://github.com/qicosmos/cinatra/pull/426) 已经修复该bug。

**Comment by 61992762** [comment]
> websocket服务端还有另外一个问题，即是接受到客户端的ping后没有重置定时器导致客户端断联。[pr426](https://github.com/qicosmos/cinatra/pull/426) 已经修复该bug。

太好了，就是此BUG让我找到了这里来

**Comment by qicosmos** [comment]
用最新的server验证即可。
