### ISSUE TITLE
refactor cinatra server to support c++20 coroutine

### ISSUE THREAD

**Issue by qicosmos** [qicosmos/cinatra#412]
- [x] 1. get/post
- [x] 2. support coroutine
- [x] 4. unit test
- [x] 5. multipart upload
- [x] 6. chunked upload/download
- [x] 7. ranges download
- [x] 8. websocket
- [x] 10.other http methods
- [x] 11.regexp url
- [x] 12.restfull
- [x] 13.static file server
- [x] 15. session, cookie
- [x] 16. timeout
- [x] 17. query
- [x] 18. form url
- [x] 19. multiple set http handler
- [x] 20. delay response
- [x] 21. examples
- [x] 22. benchmark
- [x] 23. docs
- [x] 24. server safe quit
- [x] 25. ssl
- [x] 26. regex url
- [x] 27. aspect
- [x] 28. remove old server, only keep coroutine based server :)

**Comment by qianxiaoming** [comment]
所以这是将原来的http_server改为coro_http_server的原因吗？是不是typedef一下保持向后兼容更好一些？

**Comment by qicosmos** [comment]
嗯，好建议，我加一下type define

**Comment by qicosmos** [comment]
已经提了pr

https://github.com/qicosmos/cinatra/pull/499


> 所以这是将原来的http_server改为coro_http_server的原因吗？是不是typedef一下保持向后兼容更好一些？

**Comment by qicosmos** [comment]
done
