### ISSUE TITLE
编译报错，‘_M_set_length’ is not a member of ‘std::string’

### ISSUE THREAD

**Issue by chanwoood** [qicosmos/cinatra#417]
我使用的是centos7 gcc 11.2.1。下载最新代码后，编译出错
![image](https://github.com/qicosmos/cinatra/assets/22561878/83c6641e-d641-4559-93bc-015c0cd0bf40)

**Comment by helintongh** [comment]
libstdc++.so没有更新，看起来是这个原因

**Comment by qicosmos** [comment]
gcc5 以下的libstdc++ 没有这个函数，从5.1 开始才有这个函数，你需要把libstdc++升级以下。
你也可以在这里测试各个编译器的情况
https://godbolt.org/z/nW3o5WrxT

**Comment by qicosmos** [comment]
不过可以适配一下gcc5一下的版本，稍后发一个补丁。

**Comment by qicosmos** [comment]
已经fix了，拉一下最新代码即可。

**Comment by chanwoood** [comment]
谢谢各位大佬，测试可以了
