### ISSUE TITLE
https_client

### ISSUE THREAD

**Issue by cloudfreexiao** [qicosmos/cinatra#47]
我们项目中用 cinatra 对接 微信登录需要 https client 
请问 cinatra 支持吗

**Comment by qicosmos** [comment]
cinatra is supporting http/https client now, i think it will be done this week.

**Comment by cloudfreexiao** [comment]
另外 还有个 疑问 项目之前是 vs2013 升级到 vs2017 是否可行？我用了 最新的 好像 有报错

**Comment by qicosmos** [comment]
@cloudfreexiao client可能要等这周才能完成，最晚下周搞完。

**Comment by cloudfreexiao** [comment]
好了 谢谢！！

**Comment by cloudfreexiao** [comment]
好的 我等着。。

**Comment by fawdlstty** [comment]
这个issue别关了吧，加好了再关，这样大家都能看到
