### ISSUE TITLE
项目用的intellij idea开发工具吗？

### ISSUE THREAD

**Issue by gerrywp** [qicosmos/cinatra#49]
intellij idea如何创建c/c++ project，有什么plugin吗？高手指教下

**Comment by Jackson-soft** [comment]
Clion不是有吗？

**Comment by mikeeywang** [comment]
@Jackson-soft @qicosmos  额，还是用eclipse吧。电脑装了太多IDE了，vs  2017 ide,intellij idea,还是用开源的IDE自己配，一次学习到处使用来的好！

**Comment by qicosmos** [comment]
@mikeeywang 如果你有vs2017就可以直接用啊，为啥还用eclipse

**Comment by Jackson-soft** [comment]
对啊，为啥还用eclipse

**Comment by mikeeywang** [comment]
因为想瞎折腾，不想用微软那一套msbuild,不方便移植到*unix

**Comment by qicosmos** [comment]
方便移植和IDE没啥关系，都用c++标准写代码就行。我写cinatra喜欢用vs写，然后在gcc下编译，开发效率更高。

**Comment by Jackson-soft** [comment]
现在VS2017支持CMake项目的，用标准C++写是完全没有问题的，然后想用Boost库可以直接用vcpkg安装，很方便了

**Comment by mikeeywang** [comment]
@Jackson-soft 不会配啊，新建了一个c++ "makefile project"。安装了mingw，然后在项目properties里面配置了include路径，总是提示找不到头文件！

**Comment by qicosmos** [comment]
你可以直接用vs2017，包含头文件即可，不需要什么配置。

**Comment by micfan** [comment]
vs2017 最新 release 已经支持 CMake，请妥善配置 boost 依赖，clion 不错

**Comment by qicosmos** [comment]
如果vs直接支持了cmake我可以试试用一个cmake文件了。

**Comment by qicosmos** [comment]
clion msvc vscode开发都行
