### ISSUE TITLE
是否可以让server对象的listen函数支持设置连接队列的长度？

### ISSUE THREAD

**Issue by qianxiaoming** [qicosmos/cinatra#505]
根据asio的代码，连接队列默认值是128，不过它的tcp::acceptor的listen函数确实支持设置backlog，这个参数最终会传给系统调用::listen。对于请求压力很大的服务，128可能不够，会导致连接被拒绝的错误。在linux上这个值最大可以设为/proc/sys/net/core/somaxconn中的值，即4096。

建议增加一个backlog参数，默认为0，这样在调用asio::ip::tcp::acceptor的listen函数时判断下，若不大于0则还是使用默认值asio::socket_base::max_listen_connections。

**Comment by qicosmos** [comment]
非常好的建议，如果可以的话你能帮助提这个pr吗？

**Comment by qicosmos** [comment]
我看到asio 1.24 版本(当前ciantra使用的版本), 默认的socket_base::max_listen_connections 已经是4096了

**Comment by qicosmos** [comment]
现在我们调用的listen是使用的默认值。
```
void listen(int backlog = socket_base::max_listen_connections)
```

**Comment by qianxiaoming** [comment]
我使用的MacbookPro M2 Max开发，asio也是1.24，但是我看到的是在asio的socket_base.hpp中：
```
ASIO_STATIC_CONSTANT(int, max_listen_connections
      = ASIO_OS_DEF(SOMAXCONN));
```
而SOMAXCONN定义在系统头文件socket.h中：
```
#define SOMAXCONN       128
```
Linux下的定义我再看看。谢谢。

**Comment by qicosmos** [comment]
我看了mac 下是128，linux下是4096

**Comment by qianxiaoming** [comment]
确实，在ubuntu 22.04的虚拟机里看了下是4096。
