### ISSUE TITLE
Failed to connect websocket with `Connection: upgrade`

### ISSUE THREAD

**Issue by op8867555** [qicosmos/cinatra#578]
Hi,
I'm trying to proxy a websocket endpoint via nginx. I found cinatra wouldn't accept handshakes with  `Connection: upgrade`. Probably caused by this line: https://github.com/qicosmos/cinatra/blob/d3800218692cd2cf6c6f164b5c6372526eaddd52/include/cinatra/picohttpparser.h#L887
This might be confusing since most nginx docs suggest this config:

```nginx
map $http_upgrade $connection_upgrade {
    default upgrade;
    ''      close;
}
```

According to [rfc6455 §4.2.1](https://datatracker.ietf.org/doc/html/rfc6455#section-4.2), the server should match the `Connection` value in a case-insensitive manner:

```
   4.   A |Connection| header field that includes the token "Upgrade",
        treated as an ASCII case-insensitive value.
```

**Comment by qicosmos** [comment]
Thanks for your report, will fix it soon.

**Comment by qicosmos** [comment]
You can update the code to test it again, let me know if you have any problems.

**Comment by op8867555** [comment]
Thanks for your help! It works as expected.
