### ISSUE TITLE
请问下，当链接断开时，如何获取到具体原因？

### ISSUE THREAD

**Issue by chanwoood** [qicosmos/cinatra#607]
用cinatra做websocket服务端，测试发现链接断开时会进入req.on(cinatra::ws_error, &on_ws_error)或 req.on(cinatra::ws_close, &on_ws_close); 设置的回调。如何在回调中获取到具体断联原因？比如说是服务端主动关闭、客户端主动关闭、enable_timeout为true时超时导致的断联、解包出错导致的断联等情况

**Comment by qicosmos** [comment]
你的代码是老的，用最新的代码可以得到错误信息

**Comment by chanwoood** [comment]
> 你的代码是老的，用最新的代码可以得到错误信息

以前connection的set_tag可以绑定用户自定义数据，最新的代码类似的接口了？

**Comment by chanwoood** [comment]
> 你的代码是老的，用最新的代码可以得到错误信息

以前connection的set_tag可以绑定用户自定义数据，最新的代码类似的接口了？ @qicosmos

**Comment by chanwoood** [comment]
以前connection的set_tag可以绑定用户自定义数据，最新的代码没有类似的方法了？ @qicosmos

**Comment by qicosmos** [comment]
都是协程接口了，不需要tag了。
