### ISSUE TITLE
write_websocket 使用 gzip 时协议错误

### ISSUE THREAD

**Issue by osabc** [qicosmos/cinatra#660]
Error: Invalid WebSocket frame: RSV2 and RSV3 must be clear

```cpp
co_await req.get_conn()->write_websocket("{\"code\":1,\"message\":\"hi!\"}");
```
![c3c650180913246ce23b26abdd0e988f](https://github.com/user-attachments/assets/777f9ae7-5c4e-4def-8704-668bc3b31fc7)

**Comment by qicosmos** [comment]
我稍微改造了一下测试代码：
- 启用ssl
![image](https://github.com/user-attachments/assets/a2e5015f-5e0a-464e-851b-f2eaa2efd718)
- 把server.async_start() 改成server.sync_start() 作为测试服务器。

启动postman 测试ws
![image](https://github.com/user-attachments/assets/710f0402-8f41-45d4-8913-2552e95ff94f)

测试结果正常。
你能不能重复我的测试看一下？

**Comment by osabc** [comment]
我用的就是 server.sync_start() 测试的

**Comment by osabc** [comment]
修复方法应该是 rsv1 而不是 rsv2

```
diff --git a/include/cinatra/websocket.hpp b/include/cinatra/websocket.hpp
index 50a6d79..b18b6f9 100644
--- a/include/cinatra/websocket.hpp
+++ b/include/cinatra/websocket.hpp
@@ -126,11 +126,11 @@ class websocket {
                                     bool is_client = true) {
     frame_header hdr{};
     hdr.fin = eof;
-    hdr.rsv1 = 0;
     if (need_compression)
-      hdr.rsv2 = 1;
+      hdr.rsv1 = 1;
     else
-      hdr.rsv2 = 0;
+      hdr.rsv1 = 0;
+    hdr.rsv2 = 0;
     hdr.rsv3 = 0;
     hdr.opcode = static_cast<uint8_t>(op);
     hdr.mask = is_client;
```
