### ISSUE TITLE
关于项目的一些建议

### ISSUE THREAD

**Issue by fawdlstty** [qicosmos/cinatra#7]
1、首先这个项目所用到的编译器和库都比较新，能否加入类似gcc的./contrib/download_prerequisites，一键升级、安装所需版本的编译器及第三方库到编译项目所需的版本
2、是否考虑加入static_assets，将某个路径下所有请求定位到某个文件夹，比如请求css、js这类
3、建议将http response改为基于流，直接使用res << "hello world"的方式写入返回的内容
4、服务类构造函数的那个最大并发量参数及监听时设置ip地址没必要让用户传递，建议在头文件里面取消这俩参数

**Comment by qicosmos** [comment]
我逐条说吧
1.我还不清楚怎么做，欢迎你提这个pr；
2.static_assert是编译期判断，无法用于路径之类的，运行期的assert是可以做这个事的；
3.这个建议很好；
4.最大并发量我觉得是应该开放给用户的，ip也有用，比如是127.0.0.1还是自身ip，允许自由设置更好。

**Comment by fawdlstty** [comment]
assets表示资源，不是assert断言

**Comment by fawdlstty** [comment]
最大并发量都是固定的，不用最大硬件并发量的情况几乎没有。另外监听只能监听本机，也不能监听其他电脑的ip。改这个的可能性也几乎没有

**Comment by qicosmos** [comment]
多个网卡的时候IP有多个的。

**Comment by fawdlstty** [comment]
确实很多情况需要设置IP地址，但一台电脑能同时访问的活动网络只能是一个，这种麻烦事还是不交给用户比较好，自动判断活动网络IP，或者0.0.0.0，让所有活动连接都能访问，是最好的

**Comment by qicosmos** [comment]
不要限制用户的自由，倒是可以加一个默认ip，不输入ip的时候默认就用0.0.0.0了。

**Comment by DragonQuestHero** [comment]
我也说一句...这项目的依赖实在有点夸张
17起步 干掉一堆人
boost 再挡一批
asio+11目前属于可以接受的范围
有时候要考虑向下兼容 13编译的代码是无法跑在XP2上的
13以下也是不支持C+11的

**Comment by qicosmos** [comment]
@DragonQuestHero 这个项目只支持c++17的平台。

**Comment by fawdlstty** [comment]
只支持c++17没问题，但gcc很难安装，遇到各种错误，网上搜一大圈都没找到安装方法，最终迫使我放弃使用这个库

**Comment by IronsDu** [comment]
请问如果要异步返回response（等待其他耗时"异步"操作完成），怎么做？

**Comment by qicosmos** [comment]
@IronsDu 调用response的set_delay方法，在异步完成之后再调用conn的response_now方法即可。

**Comment by IronsDu** [comment]
@qicosmos 不过 `get_conn` 函数返回的是一个裸指针，如果保证它的生命周期的安全性呢？

**Comment by qicosmos** [comment]
可以通过conn的shared_from_this把智能指针保存起来。

**Comment by Jackson-soft** [comment]
还有一点建议是，response的json输出这一块要加上去，目前我看好像只有text的输出，这个对于HTTP的API服务来说很重要

**Comment by fawdlstty** [comment]
关于监听，觉得写0.0.0.0还是不好，比较好的思路是，提供两种监听模式，只监听本机的链接，或者监听所有ip的链接

**Comment by qicosmos** [comment]
@Jackson-soft 你可以用header only的iguana来做json序列化反序列化，我用cinatra做应用的时候也是用的它。而且我觉得序列化库不属于http库，是属于应用层的东西，应该由用户去选择，而且我也提供的iguana。

**Comment by pojol** [comment]
请问在使用websocket的时候应该怎么管理conn， 使用shared_from_this存储起来嘛？ 只要不进入data_close 或者 data_error 它的生命周期就不会结束嘛？  另外是否有类似fd等标识来绑定这个conn 还是需要用户自己控制？

**Comment by qicosmos** [comment]
@pojol 有两种方法处理conn的关闭，第一种是客户端发送关闭的协议过来，服务器收到之后关闭；
第二种是服务器启动定时器，一段时间收不到请求之后服务器会主动关闭连接。
关于管理连接你可以通过一个类似于vector<weak_ptr<Conn>>来管理，要取值的时候lock一下，生命周期你可以不管，框架会管理，你只要处理好连接关闭就好。

**Comment by pojol** [comment]
@qicosmos 感谢回答：） 顺便还有几个疑问（都是在websocket场景下
我使用了本地的sesion结构保存conn 方式是
std::weak_ptr<cinatra::connection<cinatra::Socket>> connPtr_ = req.get_conn()->shared_from_this();
然后 :
1. connPtr_ 在这个类里面有可以获得的唯一标识符嘛,  目前我采用的方式是 生成一个唯一ID放在自定义的session结构中和这个conn关联起来。
2. data_begin  和 data_continue 中的req 是同一个连接嘛？ 我可以通过唯一ID找到本地存放的conn收发消息嘛？
目前我的思路是在 begin 里面建立session结构 将UUID 下放到业务层让用户和session绑定， 然后有任何业务逻辑从（continue, close, error State中获得的消息都直接下发到业务层， 由业务层去（关闭连接，发送消息 等， websocket层只控制自动断开（超时），管理session， 下发消息

**Comment by qicosmos** [comment]
data_begin 和 data_continue 中的req 始终是同一个连接。因为这是一个可重入的回调，是按ws时序回调进去的。
你为什么不把ws消息放到一个类里呢，真的需要把所有的连接管理起来吗，不过这个还是看你们实际的业务场景吧。

**Comment by pojol** [comment]
@qicosmos 谢谢：） 关于连接回答的很清楚了。   
至于为什么不把消息放在类里面， 其实是有把消息封装在类里面的， 只是我本来的框架都是基于组件的方式去设计的（所以引入http模块我也希望这个是一个黑盒的模块，让用户通过这个模块的mailbox 收发消息就可以了， 所以需要有一个id来定位这个 SessionPtr

**Comment by fawdlstty** [comment]
近期发现两个问题：第一个是示例中没有写清如何实现只接收来自本地的请求，拒绝所有其他主机的请求；第二个似乎http和https不能同时使用。假设一个网站需要同时支持http和https，那么估计需要写两个程序。另外请教下服务器转发如何实现（比如将https请求转发到一个http服务器上，客户端地址栏不变）

**Comment by qicosmos** [comment]
目前cinatra是不能同时支持http和https的，如果需要支持的话需要启动两个进程。
服务器转发的问题可以通过nginx+cinatra解决。

**Comment by qicosmos** [comment]
另外，你的建议2已经支持了

**Comment by fawdlstty** [comment]
只接收本地请求呢

**Comment by qicosmos** [comment]
关于只接受本地请求，我建议你设置一下服务器防火墙，这个事情不应该是框架去做。
另外支持这样的服务端也很少见。

**Comment by qicosmos** [comment]
@Jackson-soft 你的关于json的建议已经支持了。

**Comment by fawdlstty** [comment]
这个本身就是业务的事吧。不支持的话，是否考虑开放一个ip回调出来让用户选择哪些ip处理哪些ip不处理

**Comment by qicosmos** [comment]
@fawdlstty 可以发一个支持这样做的服务端的示例代码吗，想看看别人是怎么做的。

**Comment by fawdlstty** [comment]
C#的HttpListener，假设只需要接收本地链接，可以这样：
m_listener.Prefixes.Add ("http://localhost:1245/");
m_listener.Prefixes.Add ("http://127.0.0.1:1245/");
m_listener.Prefixes.Add ("http://::1:1245/");

**Comment by fawdlstty** [comment]
协议和端口可以不同。比如上一个是http下一个是https；主机名如果需要支持本地电脑在菊欲网中的ip，完全支持本地这种，稍微麻烦点，需要通过接口获取

**Comment by xmh0511** [comment]
@fawdlstty  这个是url的过滤 还是说程序绑定到若干个端口

**Comment by fawdlstty** [comment]
两者合二为一，或者说本身就是同一种，强行被拆分成两种

**Comment by mikeeywang** [comment]
能不能写个库的使用文档(Step by Step)？
最近改写一个项目前端用react+redux，后端想用c++，gogo之后发现了这个库，很感兴趣！
因为做了多年的c# 和 java，c++环境从大学毕业后基本没用过了，求指导。
vs 2017如何创建自己的第一个项目？

**Comment by qicosmos** [comment]
@mikeeywang 
这个库只要包含头文件就行，要注意禁用vs的4996的告警，其他的你看看main.cpp里面的例子就知道怎么用了。
关于step by step的文档在计划当中了，近期会开始写。

**Comment by mikeeywang** [comment]
@qicosmos 
好的，谢谢你的回复，持续关注~~~

**Comment by 860git** [comment]
> 

17起步有什么问题？

**Comment by 860git** [comment]
> 我也说一句...这项目的依赖实在有点夸张 17起步 干掉一堆人 boost 再挡一批 asio+11目前属于可以接受的范围 有时候要考虑向下兼容 13编译的代码是无法跑在XP2上的 13以下也是不支持C+11的

17起步有什么问题？
