### ISSUE TITLE
关于HTTP客户端功能的封装

### ISSUE THREAD

**Issue by fawdlstty** [qicosmos/cinatra#83]
#47

**Comment by Jackson-soft** [comment]
@qicosmos 客户端这一块有时间计划吗？确实也在等这个特性

**Comment by fawdlstty** [comment]
希望老大能再加一个http请求转发功能，比如接受了某个请求之后，修改一点HTTP头或者不修改，然后转发出去，类似普通代理

**Comment by micfan** [comment]
希望 http client 支持 socks5 proxy

**Comment by qicosmos** [comment]
转发我后面加个例子。

**Comment by allen2015555** [comment]
cinatra 现在已经完全支持 http/https 客户端了吗？另外，请问，有没有支持ws/wss 客户端和 http/socks5 代理的计划？

**Comment by micfan** [comment]
cinatra 现在已经完全支持 http/https 客户端了吗？另外，请问，有没有支持ws/wss 客户端和 http/socks5 代理的计划？

**Comment by qicosmos** [comment]
还没有加客户端，平时工作很忙。

**Comment by qicosmos** [comment]
done
