### ISSUE TITLE
可以尝试利用多核

### ISSUE THREAD

**Issue by daoluan** [qicosmos/cinatra#87]

**Comment by qicosmos** [comment]
具体是什么方面？现在就i时多核多线程。

**Comment by daoluan** [comment]
![image](https://user-images.githubusercontent.com/2241128/47210588-ecd1f180-d3c5-11e8-82a9-0f2aaf534d59.png)
如果利用的多核性能应该比这个高多了。

**Comment by qicosmos** [comment]
这个问题需要研究，看看怎么进一步利用asio多核特性。

**Comment by daoluan** [comment]
嗯性能可以can

**Comment by daoluan** [comment]
![image](https://user-images.githubusercontent.com/2241128/47281509-17ae8680-d60e-11e8-99ea-8c1bdfa9c710.png)
也可以参考之前写的 tinyco 思路，也是借鉴 nginx 的思想。

**Comment by fawdlstty** [comment]
这个意义应该不大。io密集型应用单线程足够，cpu密集型需要在响应请求后手动创建任务或者创建线程。nginx的思想核心在于，php等网页脚本都是单线程解析执行，速度慢，要是单线程就阻塞住了其他网页请求的响应，所以需要多线程。但cinatra因为用的是c艹，所以是偏向于io密集型，单线程足够占满几乎所有的IO。假如需要做大量的计算，可以尝试手动创建线程，然后把IO线程的资源放出来，给其他IO请求使用

**Comment by fawdlstty** [comment]
node.js就是IO密集型，IO线程处理就能在很大程度上比多线程/多进程的php的qps更高

**Comment by micfan** [comment]
每个核心跑一个 asio::io_context?

看到最新代码有 https://github.com/qicosmos/cinatra/blob/master/include/cinatra/io_service_pool.hpp，
应该像  https://github.com/0xdead4ead/BeastHttp/blob/dev/examples/reactor/main.cxx#L112 一样启动多个线程？
