### ISSUE TITLE
API 上的一个小建议

### ISSUE THREAD

**Issue by microcai** [qicosmos/cinatra#88]
server 最好能传入 io_context 的引用，方便和其他基于 asio 的库集成共用一个 io_context.

**Comment by qicosmos** [comment]
done

**Comment by microcai** [comment]
啊这？？？ 突然间修复了

**Comment by qicosmos** [comment]
增加这个功能有一段时间了，只是最近才清理issue
见单测：https://github.com/qicosmos/cinatra/blob/master/tests/test_coro_http_server.cpp#L489
