### ISSUE TITLE
默认使用多少个处理线程？

### ISSUE THREAD

**Issue by HaoLiuHust** [qicosmos/cinatra#90]

**Comment by hggq** [comment]
有没有多进程的防程序崩溃，可以专门在linux下用也行

**Comment by qicosmos** [comment]
你是说加守护进程吗？

**Comment by hggq** [comment]
是，还要有进程池和线程池，博主可以加入boost beast，顺带把通用数据库链接库加入boost 先占一个坑

**Comment by hggq** [comment]
看到 boost 1.70.0 beta 更新最大功能是beast

**Comment by micfan** [comment]
@hggq 多线程看到已经实现了，位置在 https://github.com/qicosmos/cinatra/blob/master/include/cinatra/io_service_pool.hpp#L25

不知这种方式就是“线程池”？

**Comment by qicosmos** [comment]
这个是充分利用多核，每个线程一个io_service
