### ISSUE TITLE
gcc 7.3 mingw 64（64位）, windows 10 boost 1.67, 能生成编译文件，但编译时出错！

### ISSUE THREAD

**Issue by akeyliu** [qicosmos/cinatra#91]
编译命令如下： 生成编译文件成功，但编译时出错， 出错信息如下（粘贴部分内容，主要是thread, mutex报错。）：

F:\temp\cinatra-master>cmake . -DCMAKE_C_COMPILER=gcc -DCMAKE_CXX_COMPILER=g++ -DCMAKE_CXX_FLAGS=" -m64 -Id:\\mingw64\\x86_64-w64-mingw32\\include -Id:\\mingw64\\lib\\gcc\\x86_64-w64-mingw32\\7.3.0\\include\\c++ -Ld:\\mingw64\\lib\\gcc\\x86_64-w64-mingw32\\7.3.0 -std=c++17 -lstd++ -lpthread " -DENABLE_SSL=ON -DENALBE_GZIP=ON -DCMAKE_BUILD_TYPE=Release -DBOOST_INCLUDEDIR="e:\\workspace_git\\boost64_1_67\\include" -G "MinGW Makefiles"
-- Boost version: 1.67.0
-- Found the following Boost libraries:
--   system
-- Configuring done
-- Generating done
-- Build files have been written to: F:/temp/cinatra-master

F:\temp\cinatra-master>mingw32-make -f Makefile cinatra
[ 50%] Building CXX object CMakeFiles/cinatra.dir/main.cpp.obj
In file included from F:\temp\cinatra-master\http_server.hpp:14:0,
                 from F:\temp\cinatra-master\main.cpp:2:
F:\temp\cinatra-master\io_service_pool.hpp: In member function 'void cinatra::io_service_pool::run()':
F:\temp\cinatra-master\io_service_pool.hpp:26:37: error: 'thread' is not a member of 'std'
    std::vector<std::shared_ptr<std::thread> > threads;
                                     ^~~~~~
F:\temp\cinatra-master\io_service_pool.hpp:26:37: note: suggested alternative: 'tera'
    std::vector<std::shared_ptr<std::thread> > threads;
                                     ^~~~~~
                                     tera
F:\temp\cinatra-master\io_service_pool.hpp:26:43: error: template argument 1 is invalid
    std::vector<std::shared_ptr<std::thread> > threads;
                                           ^
F:\temp\cinatra-master\io_service_pool.hpp:26:45: error: template argument 1 is invalid
    std::vector<std::shared_ptr<std::thread> > threads;
                                             ^
F:\temp\cinatra-master\io_service_pool.hpp:26:45: error: template argument 2 is invalid
F:\temp\cinatra-master\io_service_pool.hpp:28:13: error: request for member 'emplace_back' in 'threads', which is of non-class type 'int'
     threads.emplace_back(std::make_shared<std::thread>(
             ^~~~~~~~~~~~
F:\temp\cinatra-master\io_service_pool.hpp:28:48: error: 'thread' is not a member of 'std'
     threads.emplace_back(std::make_shared<std::thread>(
                                                ^~~~~~
F:\temp\cinatra-master\io_service_pool.hpp:28:48: note: suggested alternative: 'tera'
     threads.emplace_back(std::make_shared<std::thread>(
                                                ^~~~~~
                                                tera
F:\temp\cinatra-master\io_service_pool.hpp:31:24: error: no matching function for call to 'make_shared<<expression error> >(cinatra::io_service_pool::run()::<lambda(cinatra::io_service_pool::io_service_ptr)>, __gnu_cxx::__alloc_traits<std::allocator<std::shared_ptr<boost::asio::io_context> > >::value_type&)'
      }, io_services_[i]));
                        ^
In file included from D:/mingw64/lib/gcc/x86_64-w64-mingw32/7.3.0/include/c++/memory:81:0,
                 from E:/workspace_git/boost64_1_67/include/boost/asio/associated_allocator.hpp:19,
                 from E:/workspace_git/boost64_1_67/include/boost/asio.hpp:20,
                 from F:\temp\cinatra-master\use_asio.hpp:23,
                 from F:\temp\cinatra-master\http_server.hpp:2,
                 from F:\temp\cinatra-master\main.cpp:2:
D:/mingw64/lib/gcc/x86_64-w64-mingw32/7.3.0/include/c++/bits/shared_ptr.h:703:5: note: candidate: template<class _Tp, class ... _Args> std::shared_ptr<_Tp> std::make_shared(_Args&& ...)
     make_shared(_Args&&... __args)
     ^~~~~~~~~~~
D:/mingw64/lib/gcc/x86_64-w64-mingw32/7.3.0/include/c++/bits/shared_ptr.h:703:5: note:   template argument deduction/substitution failed:
In file included from F:\temp\cinatra-master\http_server.hpp:14:0,
                 from F:\temp\cinatra-master\main.cpp:2:
F:\temp\cinatra-master\io_service_pool.hpp:31:24: error: template argument 1 is invalid
      }, io_services_[i]));
                        ^
F:\temp\cinatra-master\io_service_pool.hpp:34:40: error: request for member 'size' in 'threads', which is of non-class type 'int'
    for (std::size_t i = 0; i < threads.size(); ++i)
                                        ^~~~
F:\temp\cinatra-master\io_service_pool.hpp:35:14: error: invalid types 'int[std::size_t {aka long long unsigned int}]' for array subscript
     threads[i]->join();
              ^
In file included from F:\temp\cinatra-master\request.hpp:12:0,
                 from F:\temp\cinatra-master\connection.hpp:7,
                 from F:\temp\cinatra-master\http_server.hpp:15,
                 from F:\temp\cinatra-master\main.cpp:2:
F:\temp\cinatra-master\session.hpp: At global scope:
F:\temp\cinatra-master\session.hpp:107:8: error: 'mutex' in namespace 'std' does not name a type
   std::mutex mtx_;
        ^~~~~
F:\temp\cinatra-master\session.hpp: In member function 'void cinatra::session::set_data(const string&, std::any)':
F:\temp\cinatra-master\session.hpp:38:26: error: 'mutex' is not a member of 'std'
    std::unique_lock<std::mutex> lock(mtx_);
                          ^~~~~
F:\temp\cinatra-master\session.hpp:38:26: note: suggested alternative: 'quoted'
    std::unique_lock<std::mutex> lock(mtx_);
                          ^~~~~
                          quoted
F:\temp\cinatra-master\session.hpp:38:31: error: template argument 1 is invalid
    std::unique_lock<std::mutex> lock(mtx_);
                               ^
F:\temp\cinatra-master\session.hpp:38:38: error: 'mtx_' was not declared in this scope
    std::unique_lock<std::mutex> lock(mtx_);
                                      ^~~~
F:\temp\cinatra-master\session.hpp: In member function 'T cinatra::session::get_data(const string&)':
F:\temp\cinatra-master\session.hpp:45:26: error: 'mutex' is not a member of 'std'
    std::unique_lock<std::mutex> lock(mtx_);
                          ^~~~~
F:\temp\cinatra-master\session.hpp:45:26: note: suggested alternative: 'quoted'
    std::unique_lock<std::mutex> lock(mtx_);
                          ^~~~~
                          quoted
F:\temp\cinatra-master\session.hpp:45:31: error: template argument 1 is invalid
    std::unique_lock<std::mutex> lock(mtx_);
                               ^
F:\temp\cinatra-master\session.hpp:45:38: error: 'mtx_' was not declared in this scope
    std::unique_lock<std::mutex> lock(mtx_);
                                      ^~~~
F:\temp\cinatra-master\session.hpp: In member function 'bool cinatra::session::has(const string&)':
F:\temp\cinatra-master\session.hpp:55:26: error: 'mutex' is not a member of 'std'
    std::unique_lock<std::mutex> lock(mtx_);
                          ^~~~~
F:\temp\cinatra-master\session.hpp:55:26: note: suggested alternative: 'quoted'
    std::unique_lock<std::mutex> lock(mtx_);
                          ^~~~~
                          quoted
F:\temp\cinatra-master\session.hpp:55:31: error: template argument 1 is invalid
    std::unique_lock<std::mutex> lock(mtx_);
                               ^
F:\temp\cinatra-master\session.hpp:55:38: error: 'mtx_' was not declared in this scope
    std::unique_lock<std::mutex> lock(mtx_);
                                      ^~~~
F:\temp\cinatra-master\session.hpp: In member function 'void cinatra::session::set_max_age(time_t)':
F:\temp\cinatra-master\session.hpp:66:26: error: 'mutex' is not a member of 'std'
    std::unique_lock<std::mutex> lock(mtx_);
                          ^~~~~

**Comment by qicosmos** [comment]
为什么win上不直接用vs2017编译呢？

**Comment by akeyliu** [comment]
我们一直考虑跨平台，使用codeblocks（通过不同平台的IDE版本）来编译，这样IDE在不同平台上也是一样的。现在thread, mutext的编译问题已解决，就是更换MinGW的版本，是Win32的版本更换成Posix的编译版本， 不过最后链接生成Exe文件时还有点问题，我看下是怎么链接的问题。

**Comment by akeyliu** [comment]
如果方便的话，有以下几个建议：
1、开发建议还是基于最稳定的版本来开发，比如GCC5.4对应的C++14及Boost 1.58版本；这些配置在Ubuntu16.04中只用几个apt-get命令就能安装好，也说明这些版本是最稳定的版本；
2、C++17在gcc.gnu.org中官方解释就是实验性的完全支持C++17,可能会有隐藏的问题，这会影响将这些项目直接用在生产环境中的顾虑；而C++14是完全支持；
3、做为一个成熟项目，建议补充Test的一些内容；一来方便内部测试，二来用户也可以帮忙运行一些测试，提供反馈，进一步完善这些产品；
4、做为一个完整的项目，建议补充一些安装脚本、编译脚本等，这样，有基本软件概念的人就可以简单地通过现有的脚本快速编译、运行和测试。

我有20多年的C/C++的开发经验，也一直使用C++进行开发，目前在做一些人工智能算法方面的产品。
如果有荣幸的话，看看能否加入这个项目，做点我的贡献；

**Comment by qicosmos** [comment]
1.现在cinatra只能用c++17编译，purecpp社区网站的http 服务器就是cinatra，gcc7.2+, gcc8.x下编译运行都是正常的，不用担心gcc高版本的问题。boost1.6x以上都可以。
2.现在确实缺少单元测试也缺少很多文档，一些自动化脚本也缺乏。
3.很欢迎cinatra爱好者能参与这个项目，这是开放的。
可以加入cinatra的qq群讨论：340713904

**Comment by akeyliu** [comment]
如果你只是考虑any这个c++17的特征，boost库有一个any的模块？ 不知道你这边除了Any还有其他C++17的特征不在Boost库中的吗？ 我会加入QQ群。

**Comment by qicosmos** [comment]
有很多现在boost没有的，比如c++11的可变参数模板,lambda，c++14的generic lambda, c++17的fold expression，inline variable, if constexpr。。。。

**Comment by akeyliu** [comment]
嗯，看过你两次cppcon的PPT，感觉你在元编程这块还是非常精通和深入的。 不过作为项目的使用者，会更看重产品的稳定性，是否适合提供两个版本，一个版本是实验性的，使用较为新的技术和标准，一个是稳定版本，使用较为主流的技术和版本，这样，能更大地推广项目；
比如我现在自己使用的项目，就主要使用c++标准库（c++14）和Boost库（1.58）；尽量减少基础版本和框架的不确实性。

**Comment by qicosmos** [comment]
之前很多人还希望cinatra能支持c++11，这样用的人就更多了，但是现在精力有限，能把cinatra完善好就不错了，除非平时的工作时间花一半在cinatra上，专门去做一下c++11的支持，但是这个工作量也是非常大的。

**Comment by akeyliu** [comment]
终于在MinGW中编译成功了。
说明：
1、现有版本中CMakeList.txt中链接库没有针对非MSVC的链接说明，导致链接会直接失败；补充了CMakeLists.txt补充了非MSVC的链接说明，我个人喜欢静态链接所以都指向了静态库，这样最后编译的程序没有动态库的依赖；
2、现有版本中没有CMake的调用参数，包括各类定义；我写了一个外部的build_cinatra.bat文件，方便编译；
下面附上我这边使用build_cinatra的脚本，里面包括各类配置，用户需要时，只需要调整目录即可；
【说明：上传不能是bat文件，所以文件改名为build_cinatra.txt 】


[CMakeLists.txt](https://github.com/qicosmos/cinatra/files/2751896/CMakeLists.txt)


[build_cinatra.txt](https://github.com/qicosmos/cinatra/files/2751899/build_cinatra.txt)
