### ISSUE TITLE
建议增加clang-format配置文件用以统一代码风格

### ISSUE THREAD

**Issue by Jackson-soft** [qicosmos/cinatra#92]

**Comment by micfan** [comment]
小改动请 @Jackson-soft 代劳下？

**Comment by qicosmos** [comment]
我觉得没必要专门用clang搞，规定2个或4个空格就好。

**Comment by jovany-wang** [comment]
我认为这是一个开源项目最基本的配置。

**Comment by qicosmos** [comment]
这要求使用者编译的时候还需要装clang，如果人家没装clang呢？

**Comment by qicosmos** [comment]
很多开源项目也没有专门搞个clang去format啊，和谈最基本的配置。

**Comment by jovany-wang** [comment]
我所参与过的5000stars 以上的项目，没有不配check style的。

1. clang 和clang-format是没有啥关系的， clang-format只是个代码格式化工具，并不要求装clang。
2. 即使clang-format也不要求开发者装，而是ci中enable即可。

建议多参考知名的开源项目。

**Comment by qicosmos** [comment]
现在都没有和ci集成，你可以给出一个方法，要求是让用户clone下来就能直接用这个项目，同时也能格式化好代码。
我觉得也许可以在cmakelist里面加一个编译选项，默认关闭，如果需要格式化就打开开关。

**Comment by qicosmos** [comment]
另外我不觉得你参与了万颗star的项目和我们讨论的问题有什么关系，我更期望有实际的方法，你甚至可以提pr，欢迎参与。

**Comment by qicosmos** [comment]
done
