### ISSUE TITLE
我编译的时候遇到了下面的问题，使用第一个测试用例

### ISSUE THREAD

**Issue by jacksu** [qicosmos/cinatra#94]
g++ -std=c++17 -o test test.cpp 
/tmp/ccZkW8KL.o: In function `boost::asio::detail::posix_event::posix_event()':
test.cpp:(.text._ZN5boost4asio6detail11posix_eventC2Ev[_ZN5boost4asio6detail11posix_eventC5Ev]+0x3e): undefined reference to `pthread_condattr_setclock'
/tmp/ccZkW8KL.o: In function `boost::asio::detail::posix_thread::~posix_thread()':
test.cpp:(.text._ZN5boost4asio6detail12posix_threadD2Ev[_ZN5boost4asio6detail12posix_threadD5Ev]+0x26): undefined reference to `pthread_detach'
/tmp/ccZkW8KL.o: In function `boost::asio::detail::posix_thread::join()':
test.cpp:(.text._ZN5boost4asio6detail12posix_thread4joinEv[_ZN5boost4asio6detail12posix_thread4joinEv]+0x2b): undefined reference to `pthread_join'
/tmp/ccZkW8KL.o: In function `boost::asio::detail::posix_thread::start_thread(boost::asio::detail::posix_thread::func_base*)':
test.cpp:(.text._ZN5boost4asio6detail12posix_thread12start_threadEPNS2_9func_baseE[_ZN5boost4asio6detail12posix_thread12start_threadEPNS2_9func_baseE]+0x29): undefined reference to `pthread_create'
/tmp/ccZkW8KL.o: In function `std::experimental::filesystem::v1::exists(std::experimental::filesystem::v1::path const&)':
test.cpp:(.text._ZNSt12experimental10filesystem2v16existsERKNS1_4pathE[_ZNSt12experimental10filesystem2v16existsERKNS1_4pathE]+0x14): undefined reference to `std::experimental::filesystem::v1::status(std::experimental::filesystem::v1::path const&)'
/tmp/ccZkW8KL.o: In function `uuids::uuid_system_generator::operator()()':
test.cpp:(.text._ZN5uuids21uuid_system_generatorclEv[_ZN5uuids21uuid_system_generatorclEv]+0x15): undefined reference to `uuid_generate'
/tmp/ccZkW8KL.o: In function `std::experimental::filesystem::v1::path::path<char*, std::experimental::filesystem::v1::path>(char* const&)':
test.cpp:(.text._ZNSt12experimental10filesystem2v14pathC2IPcS2_EERKT_[_ZNSt12experimental10filesystem2v14pathC5IPcS2_EERKT_]+0x6a): undefined reference to `std::experimental::filesystem::v1::path::_M_split_cmpts()'
/tmp/ccZkW8KL.o: In function `cinatra::http_server_<cinatra::io_service_pool>::run()':
test.cpp:(.text._ZN7cinatra12http_server_INS_15io_service_poolEE3runEv[_ZN7cinatra12http_server_INS_15io_service_poolEE3runEv]+0x88): undefined reference to `std::experimental::filesystem::v1::create_directory(std::experimental::filesystem::v1::path const&)'
/tmp/ccZkW8KL.o: In function `std::thread::thread<cinatra::io_service_pool::run()::{lambda(std::shared_ptr<boost::asio::io_context>)#1}, std::shared_ptr<boost::asio::io_context>&>(cinatra::io_service_pool::run()::{lambda(std::shared_ptr<boost::asio::io_context>)#1}&&, std::shared_ptr<boost::asio::io_context>&)':
test.cpp:(.text._ZNSt6threadC2IZN7cinatra15io_service_pool3runEvEUlSt10shared_ptrIN5boost4asio10io_contextEEE_JRS7_EEEOT_DpOT0_[_ZNSt6threadC5IZN7cinatra15io_service_pool3runEvEUlSt10shared_ptrIN5boost4asio10io_contextEEE_JRS7_EEEOT_DpOT0_]+0x25): undefined reference to `pthread_create'
/opt/rh/devtoolset-7/root/usr/lib/gcc/x86_64-redhat-linux/7/libstdc++_nonshared.a(thread44.o): In function `std::thread::_M_start_thread(std::unique_ptr<std::thread::_State, std::default_delete<std::thread::_State> >, void (*)())':
(.text._ZNSt6thread15_M_start_threadESt10unique_ptrINS_6_StateESt14default_deleteIS1_EEPFvvE+0x11): undefined reference to `pthread_create'
/opt/rh/devtoolset-7/root/usr/lib/gcc/x86_64-redhat-linux/7/libstdc++_nonshared.a(thread44.o): In function `std::thread::_M_start_thread(std::shared_ptr<std::thread::_Impl_base>, void (*)())':
(.text._ZNSt6thread15_M_start_threadESt10shared_ptrINS_10_Impl_baseEEPFvvE+0x5f): undefined reference to `pthread_create'
collect2: error: ld returned 1 exit status
You have new mail in /var/spool/mail/root
[root@ip-10-12-33-201 cinatra-0.07]# g++ version
g++: error: version: No such file or directory
g++: fatal error: no input files
compilation terminated.
[root@ip-10-12-33-201 cinatra-0.07]# g++-- version
bash: g++--: command not found
[root@ip-10-12-33-201 cinatra-0.07]# g++ --version
g++ (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

**Comment by micfan** [comment]
你需要
```bash
$ g++ -std=c++17  -lpthread -o test test.cpp
```

**Comment by qicosmos** [comment]
@jacksu 还有没有问题？

**Comment by alex10529** [comment]
g++ -std=c++17 -lpthread -o main main.cpp
Undefined symbols for architecture x86_64:
  "_CFRelease", referenced from:
      uuids::uuid_system_generator::operator()() in ccZRuVlZ.o
  "_CFUUIDCreate", referenced from:
      uuids::uuid_system_generator::operator()() in ccZRuVlZ.o
  "_CFUUIDGetUUIDBytes", referenced from:
      uuids::uuid_system_generator::operator()() in ccZRuVlZ.o
  "std::experimental::filesystem::v1::create_directory(std::experimental::filesystem::v1::__cxx11::path const&)", referenced from:
      cinatra::http_server_<cinatra::io_service_pool>::run()  in ccZRuVlZ.o
  "std::experimental::filesystem::v1::status(std::experimental::filesystem::v1::__cxx11::path const&)", referenced from:
      std::experimental::filesystem::v1::exists(std::experimental::filesystem::v1::__cxx11::path const&) in ccZRuVlZ.o
  "std::experimental::filesystem::v1::__cxx11::path::_M_split_cmpts()", referenced from:
      std::experimental::filesystem::v1::__cxx11::path::path<char*, std::experimental::filesystem::v1::__cxx11::path>(char* const&) in ccZRuVlZ.o
ld: symbol(s) not found for architecture x86_64
collect2: error: ld returned 1 exit status

**Comment by qicosmos** [comment]
需要安装uuid库。
