### ISSUE TITLE
长传图片base64编码被截断

### ISSUE THREAD

**Issue by wuyiwywy** [qicosmos/cinatra#99]
from中传递一个长字换串使用get_query_value接受不到

**Comment by qicosmos** [comment]
具体有多长？

**Comment by wuyiwywy** [comment]
我把一个220k左右的图片通过base64编码，然后通过get_query_value接收，只接受580左右，实际长度有4w的长度，base64 字符串是我用python库编码的，后来我试了一些长字符串，超过580的，基本上就获取不到

**Comment by qicosmos** [comment]
你可以把一个测试文件发上来，我后面试试。

另外，你怎么不用文件上传接口了，没必要转base64啊。可以参考readme里面的示例4：文件上传

**Comment by wuyiwywy** [comment]
因为之前我python接口就是上传图片的base64,因为这样方便，返回的时候我也是返回base64

**Comment by qicosmos** [comment]
发个图片文件上来。

**Comment by qicosmos** [comment]
那你用get方式又会怎么样？

**Comment by wuyiwywy** [comment]
![0ccd1c2ea7974c4a9e083872609f2ed3](https://user-images.githubusercontent.com/38450694/55860424-c6d41f80-5ba6-11e9-8a66-1470f802f757.jpeg)

**Comment by wuyiwywy** [comment]
get方式默认content长度有限制在http中

**Comment by qicosmos** [comment]
有测试的html吗？有的话也发出来。

**Comment by wuyiwywy** [comment]
![image](https://user-images.githubusercontent.com/38450694/55860568-1dd9f480-5ba7-11e9-8183-aaec8b3df35c.png)

**Comment by wuyiwywy** [comment]
你有postman这样的工具吗
或者你用python吗

**Comment by qicosmos** [comment]
OK，知道了。

**Comment by qicosmos** [comment]
你应该是用错接口了，对于post的内容都是放在body里面的，所以要这样获得post的长字符串：

auto data = req.body();
std::cout << data.size() << std::endl;

我也测试了你发的这个图片转成base64后的字符串，post发到服务端，服务端获得的body长度和base64字符串长度相同，没有漏掉数据。

**Comment by micfan** [comment]
看到在 handle "application/octet-steam" Content-Type 时，
https://github.com/qicosmos/cinatra/blob/d5f505d6f2e3430863f773e454beb771785be534/include/cinatra/connection.hpp#L425

下列代码向 static_dir 写入了 binary ？是否要去掉这个默认业务逻辑，留给 user 来自己 handle？
https://github.com/qicosmos/cinatra/blob/d5f505d6f2e3430863f773e454beb771785be534/include/cinatra/connection.hpp#L427

-----
备注下这个 MIME：
> 所有的Internet标准和大多数有关TCP/IP的书都使用octet这个术语来表示字节。使用这个过分雕琢的术语是有历史原因的，因为TCP/IP的很多工作都是在DEC-10系统上进行的，但是它并不使用8bit的字节。由于现在几乎所有的计算机系统都采用8bit的字节，因此我们在本书中使用字节（byte）这个术语。 -- 摘自 《TCP/IP详解卷一》

**Comment by qicosmos** [comment]
最开始的时候是允许用户自己控制的，不过那样接口就会显得很复杂难用，现在这种方式相当于帮用户自动保存了文件，对外只提供一个获取文件的接口，简单易用，这里是参考了java的接口。
这是之前的方式：
https://github.com/qicosmos/cinatra/blob/v0.03/main.cpp#L241

**Comment by qicosmos** [comment]
@wuyiwywy 
请问你验证过没有？有没有问题？

**Comment by micfan** [comment]
理想中要有个异步 read 接口，不懂 cinatra 和 asio

**Comment by wuyiwywy** [comment]
![image](https://user-images.githubusercontent.com/38450694/56125926-962c2580-5fac-11e9-90f4-69d4672b16bd.png)
数据长度是对的，我应该怎么获取那个字符串呢，只能自己解析那个吗

**Comment by qicosmos** [comment]
@wuyiwywy 你把这个字符串从base64再转回来，然后存文件就可以了。

**Comment by qicosmos** [comment]
@micfan 也许可以有这样一个接口，但那样的话用户需要处理不少事情，比如保存流的长度，判断是否传完了，还有错误处理，你可以看看其它语言框架是如何提供这种接口的。

**Comment by micfan** [comment]
* 以 Python 的  aiohttp server 端为例，py3有 async 关键字；对大文件，也需要加个 read buffer，从 octet-stream 里 async_read()：https://docs.aiohttp.org/en/stable/web_quickstart.html#file-uploads

  其他同步线程模型框架就不提了

  这个 trade off 有点 tricky。。。

* https://github.com/avplayer/avhttp 作为 client 端，这个循环 boost::system::error_code 的语法还不错，只是增加了 boost 依赖：

``` cpp
	// 循环读取数据.
	while (!ec) {
		std::size_t bytes_transferred = h.read_some(boost::asio::buffer(buf), ec);
		// 将下载的数据打印到屏幕.
		std::cout.write(buf.data(), bytes_transferred);
	}
```

**Comment by qicosmos** [comment]
不知道你希望控制细节的原因是什么，提供的简单直接的接口不满足你的需求吗？

**Comment by micfan** [comment]
原因是，framework SHOULD NOT 在 upload 接口直接写文件，他要 do the right thing

当然，个人业务需求足够满足

**Comment by qicosmos** [comment]
现在没有精力去增加这样的接口，等后面有精力的时候重构一下可以提供这种接口。
还有个办法，就是用websocket，websocket可以控制文件传输的细节，可以看示例代码。需要控制过程的话先用这个顶着。

**Comment by qicosmos** [comment]
@wuyiwywy 还有没有问题？
